### ISSUE TITLE
Desconexión constante de AAWireles 

### ISSUE THREAD

**Issue by pacogeno1** [cpebit/aawireless-issues#101]
**Describe the bug**
Móvil Xiaomi Mi 10, AAWireles se desconecta de Android auto cada 10 o 15 minutos,se vuelve a conectar el solo y otra vez se desconecta a los 15 minutos 

**Screenshots**

**Car (please complete the following information):**
 - Manufacturer + type

**Headunit (please complete the following information):**
 - Manufacturer + type

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung Galaxy S10]
 - Android version [e.g. 10]

**Additional context**

**Comment by Snirpo** [comment]
Duplicate #103
