### ISSUE TITLE
Desconexión con Android Auto constante

### ISSUE THREAD

**Issue by pacogeno1** [cpebit/aawireless-issues#103]
*Se desconecta de A Auto habitualmente después de estar un tiempo conectado ,al poco tiempo vuelve a conectarse el solo de nuevo ,y lugo otra vez desconexion ,está situación sucede disponiendo siempre de cobertura de datos*

**Screenshots**

**Car SsangYong Tivoli año 2020

**Smartphone 
 - Device: Xiaomi mi 10
 - Android 11
 - miui 12.5.4

**Additional context**

**Comment by juanfdp** [comment]
Me sucede lo mismo, aparentemente es por la cobertura de datos (He identificado dos sitios puntuales donde no hay buena señal en mi camino al trabajo me sucede todos los días), pero de igual forma he tenido viajes largos en donde la señal se va completamente y aun asi continua conectado sin problema

**Car Mazda CX3 2017
**Smartphone
Device: Samsung Galaxy S21+
Android 12
One UI 4.1

**Comment by pacogeno1** [comment]
Hello: I have updated the Firmware to 2.0.0 on my computer with reference AAWn7IDslmK and when connecting to the Wi-Fi network it asks me for a password, how should I act, thanks

**Comment by juanfdp** [comment]
> Most likely interference issues in your case. 2.0 firmware will make the wifi channel selectable which should help.

Hi all, I have been testing version 2 of the firmware for two weeks, the first thing I did was put the manual channel number in the wifi settings section and put it in 2.4 ghz mode, with that the connection became more stable

**Comment by Snirpo** [comment]
Duplicate #97
