### ISSUE TITLE
Music stops playing after ending a phone call

### ISSUE THREAD

**Issue by PrettyLights808** [cpebit/aawireless-issues#105]
**Describe the bug**

When I answer a phone call and hang up after, AA shows Spotify as playing music, but there's no audio

**Car (please complete the following information):**
 - 2019 VW Jetta GLI Autobahn 

**Headunit (please complete the following information):**
 - Manufacturer + type

Stock headunit 

**Smartphone (please complete the following information):**

pixel 4xl, Android 12

**Comment by Snirpo** [comment]
We cannot fix this, something fails in Android Auto.
