### ISSUE TITLE
Music lagging when GPS voice speaking / notification sound

### ISSUE THREAD

**Issue by fancybiggiejays** [cpebit/aawireless-issues#106]
**Describe the bug**
When there is music on, if a notification sound is coming or the GPS navigation voice is speaking, the music starts to lag and cuts out intermittently. Music becomes inaudible. Once notification sound or GPS navigation voice is over, music is played normally again.

**Car (please complete the following information):**
 - Peugeot 2008, 2016

**Headunit (please complete the following information):**
 - Continental NAC Wave 2

**Smartphone (please complete the following information):**
 - Device: OnePlus 8 Pro
 - Android version 11 and 12

**Comment by sopelt** [comment]
Same thing on a Citroen C4 Picasso (also Conti NAC Wave 2)  ... tested on Pixel 5 and Pixel 6 Pro ... really strange/unpleasent :)

Nothing similar when using wired AA.

Thank you for taking a closer look!

**Comment by Snirpo** [comment]
Tested on the C3 with the Motorola MA1. It has the same issues. We spent quite some time debugging this issue together with a tester. 

We tried a lot of things, buffering, dropping messages etc. It seems the head unit is extremely sensitive to latency / jitter. Nothing helped. 

So unfortunately I have to close this issue, as it's a head unit side issue which we cannot fix or work around properly.

**Comment by sopelt** [comment]
Thank you @Snirpo for thoroughly looking into this. At least I won't be tempted to buy a MA1 and try if that works ;)
It's quite a strange issue ... are the two audio streams transported via Wifi or BT?

**Comment by Snirpo** [comment]
All audio + video is transferred through WiFi (and USB). Only phone calls are routed through Bluetooth. Only video is fine, but when you run video + audio, be it music or navigation instructions, it gets choppy. Only nav instructions is ok-ish though, because it's not a constant stream.

**Comment by sopelt** [comment]
Hmmm, thanks for the info. So video + one audio stream seem to work fine (music is on 99% of the time) without any noticeable issues but the second audio stream really shakes things up ...?

**Comment by Snirpo** [comment]
No, video + audio in general is problematic. But the difference between nav instructions and music is that music is constant, nav instructions are not. You can try it on your HU: Move the map (in Google maps, Waze) around while music is playing, it's slightly laggy, and will get laggier and laggier over time. Stop music, and it's smooth as butter again.

**Comment by beastwithin78** [comment]
I have exactly the same problem on my 2017 Citroen with Continental NAC Wave 2 (with latest availaible firmware)

When i listen to music only with an AA app like simple radio or Tuning Radio, no audio issue, when using a the same time Maps or Waze i have audio Stuttering/lagging when there is and alert or GPS instructions.

I noticed that using AA Sygic app with AA music app i have no audio issue, Sygic seems to use TTS for generating GPS instructions

There also and other scenario where i do not have stuttering at all, AA Waze + Audio from car Embedded radio.

**Comment by elbubi** [comment]
Exact same issue here with Pegueot 3008 2017 (NAC2). Tried every single posible combination to no luck.

On top of that, after heavy using video + music (advancing many songs in Spotify is killer), things gets laggier and laggier to the point AAW crash and disconects from HU (or HU rejects AAW). 

Its really anoying stuff, but good to know that other devices as MA1 suffer from it too.

Hope you Snirpo and team could discover and workaround this issue, thanks for trying!
