### ISSUE TITLE
Remove tap restriction not working

### ISSUE THREAD

**Issue by Karewan** [cpebit/aawireless-issues#107]
Describe the bug:
The remove rap restriction option not working with my new phone Samsung S22 Plus running Android 12.

I have a Oneplus 6 previously running Android 10 and this option worked properly same car, same aaw firmware version.

The option is enabled, I checked with compagnon app v2.3.0 and v1.9.3 to exclude bug in the app after v2 update.

When I use the touch screen for few seconds, I get the annoying aa locking popup "safety break look the road please" (something like that)...

Car:
 - Skoda Fabia 2016

Headunit:
 - Factory Skoda Fabia unit (I don't know the name)

Smartphone:
 - Device: Samsung S22 Plus
 - Android version 12
- AAW Firmware 1.8.0

**Comment by Snirpo** [comment]
We'll check, but we might remove it anyway because it hacks into the speed "signal" which causes the GPS location to lag behind.

**Comment by Karewan** [comment]
Too bad, without this option it's impossible to select a music in the music player without getting this stupid popup... If you can find a way to keep it, that would be great !

**Comment by Snirpo** [comment]
Closing this issue, there's nothing we can do about it. It's a hack, and hacks could break at some point. All extra features will be marked experimental and only for advanced users in the next version of the app.
