### ISSUE TITLE
Hyundai: SSL issues

### ISSUE THREAD

**Issue by MrChiliCheese** [cpebit/aawireless-issues#109]
**Describe the bug**
Just got my AAWireless and I was amazed by the first paring process and testing. Completly flawless for me.
When driving and beeing on the road I get the message "Device not responding" from my head unit and Android Auto is not shown on the head units display anymore. AAWireless still shows the blue LED and the navigation (if active) is than shown on my smartphones display.
When I powercycle the AAWireless it will reconnect to phone and headunit within the minute.

**Car (please complete the following information):**
 - Hyundai Ioniq

**Headunit (please complete the following information):**
 -  Standard GEN5 Wide from LG Electronics

**Smartphone (please complete the following information):**
 - Device: Google Pixel 6 Pro
 - Android version: 11

**Comment by SentientNut** [comment]
I have the same issue after upgrading my 2021 Hyundai Sonata headunit. This updated added widescreen Android auto, which does work with my phone directly connected.

I have a Pixel 6 Pro on Android 12.

My Wireless AA unit is on firmware 1.8.

**Comment by markebert** [comment]
I also have this issue on my Hyundai Ioniq 5. I also have an issue were android auto will randomly close on the headunit and reconnect a minute later but I believe that to be an issue with the android auto app since it occurs wired or while using the aa wireless adapter. My phone is a pixel 6 running protonaosp for reference.

**Comment by Snirpo** [comment]
@SentientNut in your case switching to passthrough mode fixes it. Hyundai changed something regarding SSL, which makes normal mode not work anymore. We already have a fix, but it takes quite some code changes to fix this properly.

**Comment by MrChiliCheese** [comment]
> I have the same issue after upgrading my 2021 Hyundai Sonata headunit. This updated added widescreen Android auto, which does work with my phone directly connected.
> 
> I have a Pixel 6 Pro on Android 12.
> 
> My Wireless AA unit is on firmware 1.8.

@SentientNut, what is the version of your headunit?

**Comment by SentientNut** [comment]
> @SentientNut in your case switching to passthrough mode fixes it. Hyundai changed something regarding SSL, which makes normal mode not work anymore. We already have a fix, but it takes quite some code changes to fix this properly.

This worked like a charm. Thank you @Snirpo 

> @SentientNut, what is the version of your headunit?

DN8.USA.S5W_M.V008.001.220419 @MrChiliCheese

**Comment by Snirpo** [comment]
SSL issue will be fixed in firmware 2.1.0.
