### ISSUE TITLE
Long Lag Time for Android Auto Connection 

### ISSUE THREAD

**Issue by smbressler** [cpebit/aawireless-issues#110]
On a 2020 Subaru Outback the connection time to phone (Pixel 5 executing Android 12) varies from 30 to 60+ seconds. The settings "Start Android Auto" and "Passthrough Enable" reduced connection time however the connection time varies with long connection time lag not uncommon.

**Comment by Snirpo** [comment]
Please update to firmware > 2.0 and try to enable dongle mode from the settings in the app.
