### ISSUE TITLE
Keeps searching Android auto

### ISSUE THREAD

**Issue by PK-19-88** [cpebit/aawireless-issues#111]
**Describe the bug**
Same Problem like the Others here:
github.com/cpebit/aawireless-issues/issues/58

Android auto app on the phone keeps "searching Android auto" and to the sametime its sad car is connected on the Phone. In car headunit no respons and sad Connect a usb cable.
My Device Name is: 27fd8nKm

**Car (please complete the following information):**
 - Hyundai i30n

Headunit (please complete the following information):
- Standart Gen5 Navigation

**Smartphone (please complete the following information):**
 - Device: Oneplus 7 Pro
 - Android version 11

**Comment by PK-19-88** [comment]
After Update to 2.0 it worked

**Comment by Snirpo** [comment]
Not sure what fixed it, cause we didn't really chance anything in this regard, but good that it's fixed!
