### ISSUE TITLE
Dark mode on phone may cause issue

### ISSUE THREAD

**Issue by ZoltanAndras** [cpebit/aawireless-issues#112]
Issue: Black text in black box when adding new device makes it hard to see available devices attached a screenshot.
![Screenshot_20220501-124734_Companion Device Manager](https://user-images.githubusercontent.com/85734161/166240979-f2d22d2c-f8fd-4a9e-b402-80ac4550e2c7.jpg)

**Comment by maisondasilva** [comment]
Same here in Samsung

**Comment by serhio107** [comment]
Could not replicate with S9+ and Pixel6 on app version 3.12, the problem was fixed.
