### ISSUE TITLE
Conexion Wifi AAWireless

### ISSUE THREAD

**Issue by pacogeno1** [cpebit/aawireless-issues#113]
Hello: I have updated the Firmware to 2.0.0 on my computer with reference AAWn7IDslmK and when connecting to the Wi-Fi network it asks me for a password, how should I act, thanks

**Comment by pacogeno1** [comment]
Hello, when I try to connect to the Wi-Fi network it asks me for a Wi-Fi password,,, my equipment with reference "AAWn7IDslmK" and I cannot connect to the Wi-Fi network, could you confirm the password, please, thanks

**Comment by Snirpo** [comment]
Manually entering the wifi password is never nessecary. Please contact support@cpeb.it
