### ISSUE TITLE
Decide between 2 cell phone connections

### ISSUE THREAD

**Issue by zkidez** [cpebit/aawireless-issues#114]
I have the request to implement a Favorite list for the connection.

I have the problem that i want to connect 2 cell phones to AAW , 
1st as prefered my cellphone . But if im not drive the car it should connect to my.girlfriends  cellphone, but if we drive both it should take the prefered phone.

Greetings

**Comment by Snirpo** [comment]
This is a feature in firmware 2.0 + app 2.x.
