### ISSUE TITLE
Keep Searching for Android Auto

### ISSUE THREAD

**Issue by MaxImbrox** [cpebit/aawireless-issues#115]
**Describe the bug**
Keep Searching for Android Auto when the device is connected through USB (tried with different cables). Sometimes it works, sometimes not. Already tried all different modes through the application.

**Car (please complete the following information):**
 - Nissan Juke N-Connecta 

**Headunit (please complete the following information):**
 - NissanConnect

**Smartphone (please complete the following information):**
 - Poco F3 or Galaxy A72 
 - Android 13

**Additional context**
Device Updated to firmware 2.0.0, device name is jgpwKafX

**Comment by Snirpo** [comment]
Please ask for a replacement through support support@cpeb.it .
