### ISSUE TITLE
Nissan Juke f16 frequently disconnected 

### ISSUE THREAD

**Issue by cybrg4life** [cpebit/aawireless-issues#123]
I have a Nissan Juke f16 2020 and the infotainment system is the factory default Bosch with android auto. 
The dongle is with the latest firmware version 2.0.1 and  I tried different settings but the most that connection was live I think for 40/45 minutes. 
The developer option button, when I activate this function does noting. No other menu or settings appear? Is this normal or not? 
My phone is Poco F3 without root with latest Android auto and works without problems when connected with cable with the car.

**Comment by Snirpo** [comment]
The developer option makes the device act like the DHU (https://developer.android.com/training/cars/testing). Which makes it possible to develop AA apps on AAwireless. We'll improve the description of this setting in the next app.

About the disconnects: Please try this: https://www.youtube.com/shorts/gnlF6crZvJc on your phone. If AA disconnects when the mobile data is disconnected and reconnected, then this is the source of the issue.

**Comment by cybrg4life** [comment]
Just tested and unfortunately this is not the case.
I have no other option to test at this moment. I was very excited with this little thing... Now I am very disappointed... Just money spent for nothing. The cable connection seems the only way that is working.
Anyway thanks for the reply! All the best!

**Comment by Snirpo** [comment]
Right... so what do you want me to do, close this issue? What's the point of opening an issue without wanting it do be solved?
