### ISSUE TITLE
OTA from 1.8 to 2.x fails

### ISSUE THREAD

**Issue by kvernon** [cpebit/aawireless-issues#129]
**Describe the bug**
Howdy all!
I drive a 2019 Chevy Blazer, and the app did an update in the android store. After which, the app said a new firmware was available. Unfortunately they app continues to fail each time I attempted to update it.

**Screenshots**

**Device name (AAWireless/AndroidAuto-AAWxxxxxxx) (please complete the following information):**
 - AAWireless-5ipv0sR

**Car (please complete the following information):**
Chevrolet Blazer 2019

**Headunit (please complete the following information):**
Chevrolet Blazer 2019 (came with the car)

**Smartphone (please complete the following information):**

Device Samsung Galaxy s22+ 5g
Android 12

**Additional context**

Please also create a bug report from the help and support section in the companion app.

**Comment by Snirpo** [comment]
Does the device reboot when updating? As in, does the LED go green when starting the update?

**Comment by kvernon** [comment]
Thanks for following up @Snirpo!

I'll have to check and see when I drive next.

Can you describe a little more of what I should expect?

For now my best guess is yes at times. It seems to disconnect because...

1.  I'll see notifications in android how it connects then then starts update
2. in the car it'll disconnect from the screen, but I'll mention it doesn't do each time I tried updated.

**Comment by Snirpo** [comment]
Normally when updating the following should happen:

- Device LED goes yellow
- AA will die in the HU
- Update will complete
- Device will reboot

On some cars, possibly yours as well, when we kill AA, the HU will freak out and kills USB power. The device will then reboot during the update.

This is fixed in the 2.1.0 beta firmware. We keep AA running now while updating.

Can you try to update on a separate power source? Like an USB power adapter or PC/laptop USB port.

**Comment by kvernon** [comment]
Hi @Snirpo ,

So I tried multiple times to update where the the AAWireless device is connected to a batter, and the same issues happens.

Looking at the led, it stays flashing blue.

**Comment by kvernon** [comment]
Hi @Snirpo ,

So I tried multiple times to update where the the AAWireless device is connected to a batter, and the same issues happens.

Looking at the led, it stays flashing blue.


I also tried updating it by taking the device inside the home (no vehicle running to auto pair with). This has failed too.

Finally, I did a reset of the device (from attempting the bug report), with no success.

I've tried to grab logs, but it fails.

**Comment by Snirpo** [comment]
OK, if bug report also doesn't work, it means something on the phone is blocking access to the device. Can you possibly try the alpha version of the app: https://appdistribution.firebase.dev/i/5196d378c8e122d7

On some phones the it will try to route traffic to the device through the proxy of the mobile provider, which quite frankly doesn't make any sense. I disabled any proxy routing for OTA + bug report in the alpha version of the app.

**Comment by kvernon** [comment]
Thanks @Snirpo ,

I'll give it try later today and let you know.

**Comment by DieserMerlin** [comment]
I had this issue when my phone was connected to my home wifi network. When I removed the wifi connection (only to my home wifi, not the AAWireless hotspot) and used mobile data instead it suddenly worked. Might help

**Comment by kvernon** [comment]
> I had this issue when my phone was connected to my home wifi network. When I removed the wifi connection (only to my home wifi, not the AAWireless hotspot) and used mobile data instead it suddenly worked. Might help

I think this ended up being the issue for me! Thank you for the idea!

**Comment by DieserMerlin** [comment]
@Snirpo I don't know if you intended to fix, but I was able to install the latest update with my phone connected to my home wifi. So this seems to be fixed?

**Comment by Snirpo** [comment]
We did quite some changes in the app lately, so that's possible. I'm closing this for now, if it occurs again, this issue can be re-opened.
