### ISSUE TITLE
ATOTO: Unstable connection

### ISSUE THREAD

**Issue by Snirpo** [cpebit/aawireless-issues#133]
**Describe the bug**
Unstable connection on ATOTO headunits

**Additional context**

**Comment by Snirpo** [comment]
@PanoSpent I see you have a Pocophone F3 aka Xiaomi M2012K11AG. Can you verify if the issue you're having is not: https://www.youtube.com/shorts/gnlF6crZvJc

**Comment by PanoSpent** [comment]
No its not relevant. With or without passthrough i am having disconnections and then the aawireless unit connects again by itself. As i desicribed in the previous thread. I also sent a debug report as i mentioned.

**Comment by Snirpo** [comment]
It's very relevant, because I cannot see any difference in the logs between a disconnect because of interference/something else or the issue mentioned in the YouTube video. I'm sorry if you already tried this, but could  you please verify when toggling mobile data if the AA connection gets killed? If so I can debug further.

**Comment by PanoSpent** [comment]
@Snirpo I tried it and you are right. The behavior shown in the video you shared occurs when i am toggling the mobile data on and off.

**Comment by Snirpo** [comment]
Yes, but the same thing will happen when you loose mobile connection in areas with bad reception.

**Comment by PanoSpent** [comment]
Yeah understood! I am mentioning everything so i can help you debug this. Again to help you it has happened to me in places with very good reception in the center of the city. Now if momentarily the connection is lost i cant really check it to return the feedback to you. Is it a AAWireless-Xiaomi communication related issue or  AAWireless-Atoto communication related issue? If there is any other way i can help you with the debugging process pls ask! Thanks again!

**Comment by Snirpo** [comment]
I understand it's hard to check while driving indeed, please don't :). Do you by any chance have another phone non-Xiaomi phone which you can test on?

**Comment by PanoSpent** [comment]
I will try with a different phone form a friend and i will get back to you :)

**Comment by meeuuh92** [comment]
Hi, i can confirm this issue mith another Xiaomi phone (mi 11 lite 5g) and audi Mmi... When i lost mobile data, i lost android auto connection (sometimes like a reboot of aawireless).. it's better in pathtrough mode but not enough to solve the problem... it's too bad because aawireless connection/boot is fast and product is very fine.

**Comment by PanoSpent** [comment]
@Snirpo I am sorry for the delayed answer. I checked with one plus nord 2 and it didnt disconnect when turned off and turned back on the data. I also noticed that many times i lose the gps signal only in the wireless mode( it doesnt happen when connected with wire). 
![IMG_20220618_170942](https://user-images.githubusercontent.com/12428756/174452331-9924e606-f71d-4655-9c8e-efc490316bc7.jpg)

**Comment by Snirpo** [comment]
I have no explanation for GPS loss, except when "disable tap restriction" is turned on.

**Comment by Snirpo** [comment]
The Xiaomi issue with loosing AA connection when loosing/reconnecting mobile data connection is not something we can fix. The only one who can fix this is Xiaomi. So I'm closing this issue.
