### ISSUE TITLE
Video disconnections on Pioneer AVH-Z9200DAB starting from Aaw firmware 2.0

### ISSUE THREAD

**Issue by Cipcino81** [cpebit/aawireless-issues#136]
Starting from aawireless firmware 2.0 the screen randomly turn black with a text that tells you "to use android auto please stop your car and check your android phone." Audio still plays (navigation voice still can be heard). On firmware 1.8 this do not happen.

![message-19781077-18196725968910430675](https://user-images.githubusercontent.com/107193312/172858625-1eb22f59-e5ee-40c7-8d95-ed1de47fca3f.jpg)

AAWireless-FHASJyCK - CE:5B:16:5B:6F:EC

Toyota Celica T23

Pioneer AVH-Z9200DAB

OnePlus one Lineage 18.1 (Android 11)

I have sent you a bug report a week ago.

**Comment by joeyberkovitz** [comment]
@Cipcino81  - if you can, also please try the "MTP with retry" USB mode. It won't resolve the random disconnect, which we're working on replicating, but it may resolve the error message you're seeing and allow for an automatic reconnect.

**Comment by Cipcino81** [comment]
For now I will remain on 1.8 since I can't do further testing right now. But with 2.01 I used also MTP with force start (I think it is ) and the message still appeared, I have not tried MTP with retry though.

**Comment by Snirpo** [comment]
Should be fixed in firmware 2.0.2.
