### ISSUE TITLE
Honda: Can't re-connect to car after connecting to different car

### ISSUE THREAD

**Issue by dublus** [cpebit/aawireless-issues#139]
Cars: 2019 Honda Clarity, 2016 Honda Civic
Phones: OnePlus 7t, OnePlus 8Pro

With either of the phones or cars, after successfully connecting to one car then trying to connect to the other, the app seems to 'think' it has connected to the car (solid blue light) but the head unit stays at "Loading..." and never actually connects. By using "Troubleshooting" in the app I can get it to connect by wiping app memory and resetting the device but then it will repeat the same behavior on the other car.

**Comment by Snirpo** [comment]
You mean using the same device in two cars, or two separate devices?

Can you please mention the name(s) of the device(s)?

**Comment by dublus** [comment]
No, two different aawireless devices, one per car.

**Comment by Snirpo** [comment]
Can we please have the names of the devices (AAWireless-xxx or AndroidAuto-AAWxxx) so I can check the settings?

**Comment by dublus** [comment]
AAWireless-86jTGF8S
AAWireless-XMm6isJ3

**Comment by Snirpo** [comment]
Has this been happening since 2.0.1 or also on 1.8.0?

**Comment by Snirpo** [comment]
Sorry for the late answer. Can you possible enable passthrough on both dongles? This way we make sure Android Auto cannot detect the two devices as the same head unit.

**Comment by dublus** [comment]
We're out of town right now but I'll give it a try in a couple weeks.

**Comment by Snirpo** [comment]
No problem, thanks!

**Comment by dublus** [comment]
Set both devices to passthrough mode and after going back and forth several times the only way to connect to one after connecting to the other is to wipe the dongle memory (now connection to the second dongle is possible but the first will not connect and around in a circle you go). So, no change in behavior.

**Comment by dublus** [comment]
When using the troubleshooting option in the app it has you wipe app memory and it's my assumption (could be wrong) it does something along the lines of resetting the aawireless dongle as well. Without going through that process there is no way to complete the connection to one dongle after first completely connecting to the other (in the other car). It is clear the dongle 'thinks' the connection is complete since the light is solid blue but the car is stuck at "Loading...".

So at that point I have to go to troubleshooting in the app and answer the questions which then prompts me to clear app memory and, I'm assuming it resets or maybe just restarts the dongle. At that point the connection is made as if it's the first time, asking for permissions on the head unit. It will continue working perfectly until I get in the other car and the process starts over with having to clear app memory and whatever the app does to the dongle. Then that connection will work perfectly until I need to use the other car.

**Comment by Snirpo** [comment]
Aah ok, now it makes more sense. So clearing Android Auto data + cache seems to solve it?

**Comment by dublus** [comment]
Yes, if you look back at my very first comment that is what I said.

"By using "Troubleshooting" in the app I can get it to connect by wiping app memory and resetting the device but then it will repeat the same behavior on the other car."

**Comment by dublus** [comment]
But it's only a one-time solution until I drive the other car.

**Comment by Snirpo** [comment]
Resetting the device probably is not nessecarry. Can you verify if only resetting cache + data of Android Auto helps? You don't have to to this via troubleshooting. You can just go to phone settings --> apps --> Android Auto --> Storage and cache --> Clear storage

**Comment by dublus** [comment]
No, there's no shortcut that I can find. I've tried every variation I can think of. If you only clear app memory and cache it doesn't work. If you only have the troubleshooting section reset the dongle, it doesn't work. You have to follow what the app wants you to do, which is clear app memory/cache and the app resets the dongle (it also says to unplug and replug it but you don't have to do that). That's the only way it works.

**Comment by Snirpo** [comment]
Can you verify if the the same problem happens wired? Seems more like an Android Auto issue.
I see the "head unit manufacturer" and "head unit model" values are empty. Possibly AA thinks it's the same car, and gets confused.

**Comment by dublus** [comment]
I've gone back and forth dozens of times with usb cables and never had any problem.

**Comment by Snirpo** [comment]
OK, I'll do some digging in the AA APK to check if I can find anything.

**Comment by Snirpo** [comment]
Can you possibly get us a debug log from both cars? (help and support --> bug report). Please disable "passthrough" before.

**Comment by Snirpo** [comment]
So AA checks the uniqueness of a car based on:

CarInfoInternal r = m24325r(str, "SELECT * FROM " + str + " WHERE manufacturer = ?     AND model = ?     AND modelyear = ?     AND vehicleid = ?     AND headUnitProtocolMajorVersionNumber = ?     AND headUnitProtocolMinorVersionNumber = ?", new String[]{carInfo.f8715a, carInfo.f8716b, carInfo.f8717c, carInfoInternal.f8991u, String.valueOf(carInfo.f8719e), String.valueOf(carInfoInternal.f8971a.f8720f)});
 
On your Honda's the manufacturer and model fields are actually empty. Model year on both cars is 2016. So if the vehicle id and HU protocol version is also the same, it may be detected as the same car, and that might be messing things up.

Can you check in AA settings if there only a single car listed? (phone settings --> apps --> Android Auto --> additional settings in the app --> previously connected cars.

**Comment by dublus** [comment]
This is what I was thinking was the nature of the problem. We're leaving right now and will be back Saturday and I'll get the logs then. I forgot to mention I was able to go between a VW Atlas and the most recently connected Honda without any problem.

**Comment by dublus** [comment]
Yes, it seems there is no differentiation between the two cars/dongles. Under previously connected cars it just says "Honda" and that's it.

**Comment by Snirpo** [comment]
Hmm yeah, so this is actually an Android Auto issue. There's a very good chance if you run one dongle in normal mode (non passthrough) and the other in passthrough it will work.

**Comment by dublus** [comment]
Well, their methods leave something to be desired but we can't forget Android Auto still works in both cars without issues with a wired connection. I just turned of passthrough on the dongle in the car were in and I'll check the other one when we get back home.

**Comment by Snirpo** [comment]
Correct, but wired connection is not equal to wireless connection on the Android Auto side. There's a lot of wireless specific code in AA itself.

**Comment by Snirpo** [comment]
Is this still a problem in the latest Android Auto version?

**Comment by dublus** [comment]
I will let you know when we get one of the cars back from the shop. They've
had it for almost a month. "Supply chain issues". Thanks for remembering.
