### ISSUE TITLE
Hyundai Palisade Not work after update 2.0.0 firmware 

### ISSUE THREAD

**Issue by changiri** [cpebit/aawireless-issues#140]
**Describe the bug**
It worked fine in version 1.7.x, but does not work in version 2.0.0. After the USB connection attempt popup, a popup indicating that the phone is not responding appears from the head unit.

**Device name (AAWireless/AndroidAuto-AAWxxxxxxx) (please complete the following information):**
 - AndroidAuto-AAWoNdIEcTS

**Car (please complete the following information):**
 - HYUNDAI PALISADE

**Headunit (please complete the following information):**
 - 5 GEN 

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S21
 - Android version 12

**Additional context**

Please also create a bug report from the help and support section in the companion app.

**Comment by Snirpo** [comment]
Please enable passthrough mode in the settings, after a recent HU update, it will not work anymore in normal mode. Will be fixed in 2.1.0.

**Comment by changiri** [comment]
Ok, I'll try. Thank you for reply.

2022년 6월 12일 (일) 오후 3:25, Chiel Prins ***@***.***>님이 작성:

**Comment by Snirpo** [comment]
Thanks!
