### ISSUE TITLE
Add resolution change function

### ISSUE THREAD

**Issue by bhmin-dev** [cpebit/aawireless-issues#142]
Hello. You work hard.
First of all, thank you for making such a great device.

Can you add the ability to change the resolution to the AAWireless App?
The resolution of the Head Unit of my car is 1280x720, but it seems that the resolution of Android Auto is set to 800x480.
(When I save a video in the Android Auto Developer menu, it is saved as 800x480.)
So the screen or icons are not displayed smoothly.
The same goes for changing the video resolution in the Android Auto developer menu on my phone.
When I test with DHU (Desktop Head Unit) in Android Studio, it is solved by combining the Resolution and DPI changes in the config file.
There is a DPI change menu in the AAWireless app, can you please add a menu to change the resolution?

Thanks.

**Comment by Snirpo** [comment]
If the HU supports multiple resolution for AA, we can do this. However, we cannot guarantee it will actually work. These kinds of settings come with big disclaimers :)
