### ISSUE TITLE
Cannot update from version 1.8.0 to 2.0.2

### ISSUE THREAD

**Issue by jojo7v** [cpebit/aawireless-issues#144]
**Describe the bug**
My AA dongle currently has version 1.8.0 installed, and version 2.0.2 is available.
My phone has the latest app (2.17.0).
When I try to update, the download works fine.
While installing, it stops differently between 67% and 74%. The update notification just disappear and the error "Update failed" is shown in the app.

**Screenshots**
![Screenshot_20220624-140744_AAWireless](https://user-images.githubusercontent.com/108131978/175535682-39e332ba-9b50-42de-94fb-0729e575e4a8.png)

**Device name: AAWireless
 - Manufacturer + type

**Car (please complete the following information):**
 - Manufacturer + type: Audi A3 8V

**Headunit (please complete the following information):**
 - Manufacturer + type: original display from Audi

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S10
 - Android version: 12

**Comment by Snirpo** [comment]
Please try to update while connected to a separate power source (USB charger). You car radio most likely kills power to the device when AA gets killed.

**Comment by jojo7v** [comment]
In the meanwhile, I did a factory reset of the AAWireless and uninstall and reinstalled the app, and having version 1.8.0 on the device, I get "No update available".

**Comment by jojo7v** [comment]
> Please try to update while connected to a separate power source (USB charger). You car radio most likely kills power to the device when AA gets killed.

This was a good advice. Thanks Snirpo!

In the meanwhile, I reset the device and my phone. After that, my phone always said there's no update available. Trying with my tablet and AAWireless on USB charger worked!

It looks like the apps saves the update state somewhere so that it is restored even after an uninstall/install. In my case, it was bad, since a bad state was saved.

**Comment by Snirpo** [comment]
This issue will be fixed in 2.1.0, by not killing AA when updating. So updates can be run in parallel while AA is running :)

**Comment by jojo7v** [comment]
> This issue will be fixed in 2.1.0, by not killing AA when updating. So updates can be run in parallel while AA is running :)

It sounds really great!
