### ISSUE TITLE
LED state explanation inside the app

### ISSUE THREAD

**Issue by Basiswissen** [cpebit/aawireless-issues#146]
I would like an explanation about what the different LED states are meaning. This should be included in the app for offline troubleshooting.

At the moment there is just a troubleshooter which tells you what to do but doesn't give further explanation what is actually happening.

**Comment by Snirpo** [comment]
Better explanation of LED's planning for app version 3.0

**Comment by Snirpo** [comment]
Closing this issue, version 3.0 of the app will have an UI overhaul with clearer descriptions / images.
