### ISSUE TITLE
Unable to access syslog

### ISSUE THREAD

**Issue by dynasticorpheus** [cpebit/aawireless-issues#148]
**Describe the bug**
Unable to access log using below URL using Android / Chrome despite disabling 4G. Any best practices you can share perhaps?

http://10.42.1.1:8000/syslog

**Comment by Snirpo** [comment]
Not sure why you need this? Debug logs can be sent to us by using the help and support --> bug report functionality. It will call the same endpoint.

**Comment by dynasticorpheus** [comment]
I have more frequent drops after upgrading to most recent firmware hence interested what's there to see. IT person myself so step 1 is doing some root cause analysis myself before logging a ticket :)

**Comment by Snirpo** [comment]
Ah OK, no problem. You can try with a PC, wifi password is the uppercased sha1 of the wifi SSID (or Bluetooth name).
