### ISSUE TITLE
V2.0.2. Disconnects in Audi A8

### ISSUE THREAD

**Issue by crostonblue** [cpebit/aawireless-issues#152]
Since updating to v2.0.2 my AAWireless device restarts 1 min after starting the car and then every 20 mins, I had no issues with v2.0.1

2021 Audi A8

Samsung Galaxy S20 Ultra

**Comment by Snirpo** [comment]
Please shoot in a bug report via the app (help and support --> bug report). Seems same like #149

**Comment by crostonblue** [comment]
Hi, bug report sent

**Comment by crostonblue** [comment]
Hi, I've done a factory reset, deleted the App, removed all connections from my MMI, then started again as if the u it was brand new - same result, still dropping out.

How do I go back to V2.0.1, as that version worked perfectly.
