### ISSUE TITLE
Unable to upgrade firmware.

### ISSUE THREAD

**Issue by 80kk** [cpebit/aawireless-issues#153]
**Describe the bug**
I am trying to upgrade my dongle using my Pixel4 mobile (I've also tried Pixel5 and 6). When I open an Upgrade menu in the app it says:
`Update available`, `Current: 2.0.0`, `Latest: 2.0.2`. When I tap on `Start download` it then starting downloading and turns Current to `1.2.1`. After it finish downloading it is turning back Current to `2.0.0`

**Screenshots**
https://ibb.co/Zznd9Q0
https://ibb.co/DbXVPBD

**Device name (AAWireless/AndroidAuto-AAWxxxxxxx) (please complete the following information):**
` AAWireless-h1UiSQwx`

**Car (please complete the following information):**
`Opel/Vauxhall Insignia Mk.2 2018-`

**Headunit (please complete the following information):**
`Navi 900 IntelliLink`

**Smartphone (please complete the following information):**
 - Device: `Google Pixel4`
 - Android version: `12 with latest security patch`

**Additional context**

Please also create a bug report from the help and support section in the companion app.
- I did create a bug report and I did see that this issue has been fixed in the last Android app version but unfortunately it didn't fix it for me. I've deleted cache, restarted app but with no luck.

**Comment by Snirpo** [comment]
Sorry I missed this issue. Good that it's fixed :)
