### ISSUE TITLE
Connection Drops Immediately with 2017 VW Head Unit

### ISSUE THREAD

**Issue by glenclayton** [cpebit/aawireless-issues#155]
**Describe the bug**
Cannot maintain connection to VW Head Unit
Steps
 - Head Unit -> Press Android Auto Text
 - Head Unit -> Android Auto Text flashed white (usually preceeds a sucessful connection)
 - Phone -> Continue Setup on Head Unit
 - Head Unit -> Disconnected
 - AAWireless - flashing blue

**Screenshots**

**Device name (AAWireless/AndroidAuto-AAWxxxxxxx) (please complete the following information):**
 - Google Pixel 6 - Latest Android 12 and AA (Stock, not beta channel)
 - AAWireless-fJPtAkS7 (2.0.2 update)

**Car (please complete the following information):**
 - VW Golf 2017
**Headunit (please complete the following information):**
 - Stock VW

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung Galaxy S10]
 - Android version [e.g. 10]

**Additional context**

Please also create a bug report from the help and support section in the companion app.

**Comment by Snirpo** [comment]
Did the same thing happen on firmware 1.12.0?

**Comment by glenclayton** [comment]
I've just got the device so only have tried with 2.0.1 and 2.0.2 - same in both cases.
