### ISSUE TITLE
Please add volume adjustment feature if possible

### ISSUE THREAD

**Issue by dionorgua** [cpebit/aawireless-issues#157]
I'm using AAWireless with VW MIB STD2 PQ head unit. Everything works fine except one thing: volume is too loud when using AAWireless together with Youtube Music.

Even on lowest possible head unit volume music is a bit louder than I expect. It mostly ok while driving, but too loud when baby sleeps in car. 

Without AAWireless (when phone is connected directly using USB cable) I'm able to lower volume using phone volume control. But when using AAWireless it looks like phone volume is ignored.

It would be cool if AAWireless can adjust volume on it's own. Maybe just single 'amplify' setting (something like 0.6-0.8 will be enough for me).

Thanks a lot!

**Comment by Snirpo** [comment]
Unfortunately we cannot do this, we're just passing through audio data.
