### ISSUE TITLE
Cupra formentor - appcrash every once in a while

### ISSUE THREAD

**Issue by ori-rezonate** [cpebit/aawireless-issues#158]
**Describe the bug**

**Screenshots**

**Device name (AAWireless/AndroidAuto-AAWxxxxxxx) (please complete the following information):**
 - Manufacturer + type

**Car (please complete the following information):**
 - Manufacturer + type

**Headunit (please complete the following information):**
 - Manufacturer + type

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung Galaxy S10]
 - Android version [e.g. 10]

**Additional context**

Please also create a bug report from the help and support section in the companion app.

**Comment by EVPower2k13** [comment]
Hi, I randomly get disconnected when running android auto. Append more on
many short trips within the same day.
The light stays solid white.

On the firmware 1.8, I need to unplug the box and replug it.

Now with the new firmware 2.0.2 and the AAWireless app, I just need to
click on restart and the box is working again after 15 seconds.
Just not convenient to do it often.

AAWireless-gJruCwnU
Hyundai Kona 2021 EV
Samsung S10e Android 12

Thanks.

**Comment by Snirpo** [comment]
Please contact support for help.
