### ISSUE TITLE
False Update

### ISSUE THREAD

**Issue by ann4belle** [cpebit/aawireless-issues#159]
**Describe the bug**
The app wants me to update from 2.0.2 to 1.12.0.

**Screenshots**
![image](https://user-images.githubusercontent.com/18199611/180992747-1f8774e5-1735-42c9-9fb6-74b51581768d.png)

**Device name (AAWireless/AndroidAuto-AAWxxxxxxx) (please complete the following information):**
 - AAWireless-VXbw1Lod

**Car (please complete the following information):**
 - 2019 Chrysler 300

**Headunit (please complete the following information):**
 - Unknown, can check later if necessary

**Smartphone (please complete the following information):**
 - Device: Google Pixel 6 Pro
 - Android version 12 (build SQ3A.220705.003.A1)

**Comment by imbamo** [comment]
same exact problem, after updating 1.12.0 it does not detect other updates

**Comment by bpsmicro** [comment]
This was covered in the XDAForums discussion:
`This is intended actually. There are problems with firmware 2.x and Uconnect, so we decided to hardcode latest firmware for UConnect to 1.12.0. Almost every day support has to downgrade a few devices to 1.12.0.`

(Chrysler == UConnect)

**Comment by Snirpo** [comment]
@bpsmicro Correct! If you don't have any issues, you don't have to downgrade. Check #128 for details.

**Comment by ann4belle** [comment]
So does this mean that I won't get any updates past 1.12.0, even if I'm not experiencing any issues?

**Comment by Snirpo** [comment]
Only temporarily until we figured out what's wrong.

**Comment by ann4belle** [comment]
I see. Is there any sort of log file I can provide that would help, since I'm not experiencing any problems?
