### ISSUE TITLE
Audio multiplexing not perfect when waze talk when Deezer is streaming

### ISSUE THREAD

**Issue by Le-Kiki** [cpebit/aawireless-issues#160]
**Describe the bug**
First great thanks for this great feature that has bought Wireless Android Auto to my car.

All is working like a charm  except an audio issue when waze speaks to indicate directions while Deezer is streaming music

**Device name (AAWireless/AndroidAuto-AAWxxxxxxx) (please complete the following information):**
 - AAWireless/AndroidAuto-AAWW99iJbfk

**Car (please complete the following information):**
 - Citroën Grand C4 Spacetourer

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S22 Ultra
 - Android version 12

**Additional context**
When the phone is directly wired connected to the car, the multiplexing issue never happens.

Please also create a bug report from the help and support section in the companion app.

**Comment by Snirpo** [comment]
Unfortunaly this is a known issue on NAC Wave2 HU's, please check #106
