### ISSUE TITLE
Dropouts and rollback to 1.12.0 without notice 2015 Ram 1500.

### ISSUE THREAD

**Issue by StreetChariot** [cpebit/aawireless-issues#162]
The AA App downgraded the firmware the other day back to 1.12.0 with no updates available.

Since then, frequent disconnects and app decides to flash back and fourth regarding the connection or no connection.

Was working great before the rollback from 2.0.2 back to 1.12.0.

**Comment by Snirpo** [comment]
Weird, can't explain this. We locked UConnect to 1.12.0 because of #128 . Can you post your device name? I'll enable the latest beta, should work fine again.

**Comment by StreetChariot** [comment]
xOEQvmYK should be the ID.
________________________________

**Comment by StreetChariot** [comment]
Also I have a 2019 challenger Uconnect 8.4 in my 2015. :)

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Snirpo** [comment]
@StreetChariot Develop firmware is enabled, please switch to default USB mode, all other USB modes or not nessecary anymore.

**Comment by StreetChariot** [comment]
Thanks Chiel. I'll definitely check when I'm back in the truck.

Interestingly enough, when I set pass through back to on, it worked on 1.12.0 (had it turned off when it was on 2.0.2..

I'll reset the settings when I get the beta installed and let you know.

Thanks again!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by StreetChariot** [comment]
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Snirpo** [comment]
Should be fixed in 2.1.0, if not please open a new issue.
