### ISSUE TITLE
Fiat tipo 2017 1.12.0 is back.

### ISSUE THREAD

**Issue by naz062** [cpebit/aawireless-issues#163]
**Describe the bug**
The AA App downgraded the firmware the other day back to 1.12.0 with no updates available.

Since then, frequent disconnects and app decides to flash back and fourth regarding the connection or no connection.

**Screenshots**

**Device name (AAWireless/AndroidAuto-AAWxxxxxxx) (please complete the following information):**
 AAW372Tx7Xn

**Car (please complete the following information):**
 - FIAT TIPO 2017

**Headunit (please complete the following information):**
 - Uconnet 7

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung A52S 5G ]
 - Android version [e.g. 12]

**Additional context**

Please also create a bug report from the help and support section in the companion app.

**Comment by Snirpo** [comment]
I enabled 2.1.0 for you, can you please update?
