### ISSUE TITLE
Rollback to firmware 1.12.0. Won't download most recent update

### ISSUE THREAD

**Issue by PseudonymSam** [cpebit/aawireless-issues#164]
I have a 2019 RAM 1500, with uconnect, using a Pixel 6 Pro running Android 12. I set up device, no android auto function at firmware 1.12.0(Device Not Recognized). It said update to latest software, 2.0.2, I updated and android auto worked beautifully. Then suddenly it reverted back to 1.12.0 and back to no function at all. my device name is: cg4Rz9Wy.

p.s. when I open the app, it says that there is a system update to 2.0.2, I start the download, then where it said 2.0.2 it changes to 1.12.0 and then the update never finishes. It is stuck in this loop for a while. factory reset, cache clearing and storage clearing do nothing to fix this.

![Screenshot_20220818-205016](https://user-images.githubusercontent.com/111553276/185714471-1bf44e90-4dae-4a7e-af30-0c52f44d095b.png)

![Screenshot_20220818-205023](https://user-images.githubusercontent.com/111553276/185714510-9d1029f2-ecc8-488f-984f-c041f3719466.png)

![Screenshot_20220818-205029](https://user-images.githubusercontent.com/111553276/185714525-1e81eab0-a0cb-4751-a44d-089616e03795.png)

**Comment by Snirpo** [comment]
Enabled the latest firmware for you (2.1.0), you should be able to update.

**Comment by gcnunez** [comment]
I'm having the exact same issue

**Comment by gui-jasmin** [comment]
I have the exact same issue, RAM 1500 2019. Was recognized on 2.x firmware and got reverted back to 1.12.x and it is not recognized anymore

**Comment by Snirpo** [comment]
Everyone is now able to update to 2.1.0, please update to 2.1.0.
