### ISSUE TITLE
Can't download OTA update

### ISSUE THREAD

**Issue by zavinator** [cpebit/aawireless-issues#166]
**Describe the bug**
I can't download the latest OTA update 2.1.0 with the AAWireless app. When I click "Start download" nothing happens - no download and no error message. 
I've tried both data connections (WiFi, mobile data). I had no problem when downloading the previous version 2.0.2 and the only things that has changed is the Android system version (12 -> 13) and apk version.

**Smartphone (please complete the following information):**
 - Device: Google Pixel 4a
 - Android version 13
 - Apk version: 2.22.0

**Additional context**
My device name: TEWveppu
There is not latest version info, but it still notifies me about a new version.
![Screenshot_20220824-094519](https://user-images.githubusercontent.com/7337247/186362639-4c879484-8194-4283-b44f-f8ba00cd55be.png)

**Comment by Tagyourout** [comment]
Same issue here. OTA download initiates then stops.
Google Pixel 6 Pro Android 13.

**Comment by mako8866** [comment]
Same issue.

Pixel 6 Pro
Android 12

**Comment by matuszajac** [comment]
Same here. Android 12 OnePlus 9 pro.
Can't download update file. Latest APK version from play store. 2.22

**Comment by maddenfederico** [comment]
Same here. Pixel 6 Android 13 apk 2.22

**Comment by Raudi1** [comment]
Seems like it's a pixel issue. Same on my pixel 6 with latest Android and aawireless app from Google play.

**Comment by Macronot** [comment]
Same issue Oneplus Nord Android 12.

**Comment by olmuss** [comment]
It is not the fault of the mobile, I have Samsung M52 5g and the same problem, it does not download

**Comment by 0n3-70uch** [comment]
Hi same problem here.
Pixel 6 Pro / Android 13 / AAwireless 2.22

**Comment by Snirpo** [comment]
We are looking into it.

**Comment by minor69** [comment]
Samsung Galaxy S2 Ultra 5g Same Problem

**Comment by bossarts** [comment]
Galaxy S10, same issue...

**Comment by Snirpo** [comment]
For most of you this should be fixed now. The app caches data from the backend, so it could take up to 4 hours to correct itself.

**Comment by Macronot** [comment]
+1 fixed

**Comment by zavinator** [comment]
fixed

**Comment by 0n3-70uch** [comment]
All fine now. Thanks

**Comment by minor69** [comment]
Very Thx...
