### ISSUE TITLE
Unable to download firmware 2.1.0

### ISSUE THREAD

**Issue by zthalji** [cpebit/aawireless-issues#167]
**Describe the bug**
Unable to download firmware 2.1.0. Download window opens but nothing happens. 

**Screenshots**

**Device name (AAWireless/AndroidAuto-AAWJT8ca9GP) (please complete the following information):**
 - AAwireless AAWJT8ca9GP

**Car
 - Mercedes GLC 2020

**Headunit
 - Mercedes MBUX

**Smartphone
 - Device: Samsung Galaxy S20]
 - Android version 12

**Additional context**

Please also create a bug report from the help and support section in the companion app.

**Comment by Snirpo** [comment]
Rolling out a new version of the app now which should fix this issue.

**Comment by bwshockley** [comment]
I'm on version 2.23. cannot download the 2.1.0.

**Comment by merdely** [comment]
I cannot download the new firmware either.
2019 Audi S5
Device: Google Pixel 6 Pro
Android: 13
App Version: 2.23.0

I've tried on mobile, on Wifi, and on Wifi over a VPN.  I've tried using my router's DNS and using Quad9.net's DOH DNS (incase my DNS filtering was causing any issues).

When I click Start Update, I see: "Warning: If you have any VPN enabled, please disable the VPN..."  Unless specifically testing over the VPN, I do not have a VPN enabled.

**Comment by Snirpo** [comment]
@merdely Seems the download is working fine, but updating is not working?

**Comment by Snirpo** [comment]
@merdely Can you possibly post a screenshot?

**Comment by bwshockley** [comment]
@Snirpo - The downloading does not work.  App works fine.  It reports that it found an update from 1.8.0 to 2.1.0.  I tap to update and it warns me that I'm on a metered network, I tap download now, and it acts like it's trying.  It states "Download 0%"...and a notification also pops up stating it is downloading at 0%...it sits for about 5-10 seconds, never going over 0%.  Then it closes and the screen is right back to update available, showing my 1.8.0 and it found 2.1.0.

**Comment by merdely** [comment]
@Snirpo Attached.
![Screenshot_20220830-093752](https://user-images.githubusercontent.com/6376795/187452642-0d16dffb-db30-4a39-9d08-2aff8792cfc0.png)
![Screenshot_20220830-093739](https://user-images.githubusercontent.com/6376795/187452643-eda5a0e3-3b81-453f-a4d7-4a719e346260.png)

**Comment by merdely** [comment]
> @Snirpo - The downloading does not work. App works fine. It reports that it found an update from 1.8.0 to 2.1.0. I tap to update and it warns me that I'm on a metered network, I tap download now, and it acts like it's trying. It states "Download 0%"...and a notification also pops up stating it is downloading at 0%...it sits for about 5-10 seconds, never going over 0%. Then it closes and the screen is right back to update available, showing my 1.8.0 and it found 2.1.0.

I used to see this exact behavior, then it started giving me the VPN error along with the "An error occurred, please try again" message in my screenshot.

**Comment by bwshockley** [comment]
Video of my process.
https://user-images.githubusercontent.com/5291634/187453887-5586df39-9ec8-43fa-ad9a-1647f8cbbf47.mp4

**Comment by DogeTrento** [comment]
Same here, no download...😔

**Comment by fmuniz** [comment]
Exact same here, but I'm on 2.0.2

> @Snirpo - The downloading does not work. App works fine. It reports that it found an update from 1.8.0 to 2.1.0. I tap to update and it warns me that I'm on a metered network, I tap download now, and it acts like it's trying. It states "Download 0%"...and a notification also pops up stating it is downloading at 0%...it sits for about 5-10 seconds, never going over 0%. Then it closes and the screen is right back to update available, showing my 1.8.0 and it found 2.1.0.

**Comment by Snirpo** [comment]
@merdely It seems in your case the download has already been downloaded, but the update itself doesn't work. Maybe a stupid question, not to offend you, but the device is on and you are in vicinity of the device right?

@bwshockley Thanks for the recording. Can you confirm the version of the app? Is it 2.22.0 or 2.23.0? It's on the home screen, but I can't see it fully on the video recording.

**Comment by bunicb** [comment]
Same here, on app 2.23.0.
Starts, says 0%, and then just a short notification download failed, and it immediately disappears.

**Comment by Snirpo** [comment]
@bunicb Can you also download the dev app https://appdistribution.firebase.dev/i/210fc06c9667e5f8 , run the download again and either post the MAC address or name of your device (AAWireless-xxxx or AndroidAutoAAW-xxxx)?

**Comment by bunicb** [comment]
Hi, just tried it in dev.
Device name is AndroidAuto-AAWhXWWlTzo

**Comment by merdely** [comment]
> @merdely It seems in your case the download has already been downloaded, but the update itself doesn't work. Maybe a stupid question, not to offend you, but the device is on and you are in vicinity of the device right?

Oh my. I'm so embarrassed.  I swear I was having the exact same problem as @bwshockley for days and days. I did not notice that it changed to say "Download complete".

Sorry to waste your time. I went out to my car and after 3 or 4 failures, it succeeded.

Thanks for your help.

**Comment by Snirpo** [comment]
@merdely No problem. 3 failures does not sound right though. We might switch back to the old way of updating. What we are doing right now is piggybacking on the connection of Android Auto itself, but that doesn't seem to work correctly for everyone. A safer (albeit slower) way of updating might be to just kill Android Auto beforehand.

@bunicb Thanks. May have found the issue. Will push a new version dev version of the app tomorrow.

**Comment by bwshockley** [comment]
@Snirpo - Still need me to install the -dev build?  OR should I wait until a new version is ready tomorrow?

**Comment by Snirpo** [comment]
@bwshockley the dev version has quicker (immediate) updates compared to the production (Play Store) version. So for testing that's the way to go :)

**Comment by danbantha** [comment]
Same issue 
![Screenshot_20220831-080058_AAWireless](https://user-images.githubusercontent.com/112520702/187551813-708df839-8f6f-4ba7-815e-cda8759b3b71.jpg)

**Comment by bwshockley** [comment]
> @bwshockley the dev version has quicker (immediate) updates compared to the production (Play Store) version. So for testing that's the way to go :)

I tried updating via the dev version this morning.  Same results. AAWireless-PX4QToCs

**Comment by Snirpo** [comment]
Yes, easy :) Haven't pushed it yet.

**Comment by Snirpo** [comment]
New build is available now

**Comment by bwshockley** [comment]
2.24 dev build fixed the issue for me. 2.1.0 downloaded and installed fine.

**Comment by Snirpo** [comment]
@bwshockley Great! Download was broken for all batch 1 and 2 devices. Should be fine again now. Will push it into production tomorrow.

**Comment by taylorsdesigns** [comment]
Sounds resolved now but I had to download off of wifi, took like 3 tries fyi

How do I know which batch my device is in

**Comment by bunicb** [comment]
Yep, worked for me too on 2.24.0.

**Comment by Snirpo** [comment]
@taylorsdesigns If you post the name of your device, I can check.

**Comment by Snirpo** [comment]
Since it seems to be fixed, I'm closing this issue and rolling out 2.24.0. If you're still experiencing issues with OTA, please open a new issue.

**Comment by taylorsdesigns** [comment]
@snirpo AAWireless-Bj1T9rTm

**Comment by Snirpo** [comment]
@taylorsdesigns that's a gen2 device, so should not be affected.
