### ISSUE TITLE
Possible solution for micro disconnections in Xiaomi/Redmi/POCO smartphones few minutes from vehicle start

### ISSUE THREAD

**Issue by IngMoscato** [cpebit/aawireless-issues#171]
**Describe the bug**
Everytime I start my car my smartphone connects to AAWireless receiver and, after few minutes, a micro disconnection happens.
After few seconds the smartphone reconnect properly to receiver and connection remains stable.

**Device name (AAWireless/AndroidAuto-AAWxxxxxxx) (please complete the following information):**
 - AAWireless

**Car (please complete the following information):**
- Kia Sportage

**Smartphone (please complete the following information):**
 - Device: POCO F4 GT
 - Android version 12

**Possible solution
- The solution I found is to set MIUI battery restictions to "no restrictions" for AAWireless app.
   It's about one week the problem doesn't happen anymore.

**Comment by Snirpo** [comment]
Are you using start / stop? Please provide the name of the device (AAWireless-xxxxxx or AndroidAuto-AAWxxxxxxx).

**Comment by IngMoscato** [comment]
> Are you using start / stop? Please provide the name of the device (AAWireless-xxxxxx or AndroidAuto-AAWxxxxxxx).

Yes, my device is AndroidAuto-AAWNrJ9wZaY

**Comment by Snirpo** [comment]
In that case it makes sense indeed. Unfortunaly we have no control over power / battery saving. Technically it is possible, but the app will be banned from the Play Store if we do that. We'll add an extra disclaimer in start / stop settings to disable any battery saving.

**Comment by IngMoscato** [comment]
> In that case it makes sense indeed. Unfortunaly we have no control over power / battery saving. Technically it is possible, but the app will be banned from the Play Store if we do that. We'll add an extra disclaimer in start / stop settings to disable any battery saving.

In my case my infotainment system of my car doesn't know anything about start/stop function and, how the rest of cars in the world, simply turns off automatically if you have turned off the car after min 10/15 min. 
The disconnections happen regardless car is moving or is stopped. 
The sequence is: You turn on the car -> smartphone connects -> after few minutes passed-> receiver disconnects and reconnects regardless you are moving or not

**Comment by R4ngerMibex** [comment]
I also had the same issue on a poco f4 GT. Eventually my solution was to buy a different brand. Works okay now.

**Comment by Snirpo** [comment]
Different brand of phone you mean?

**Comment by R4ngerMibex** [comment]
Yeah, I got fed up with it in the end. Cheap phone for a reason.

**Comment by serhio107** [comment]
phone side issue
