### ISSUE TITLE
Audio dropouts

### ISSUE THREAD

**Issue by abagc** [cpebit/aawireless-issues#173]
**Describe the bug**
 - I have seemingly random audio dropouts every 0.5-3 minutes in Spotify and CloudBeats (cloud player), which last about 0.5 seconds. This problem never occurs with a cable connection.

**Screenshots**

**Device name (AAWireless/AndroidAuto-AAWxxxxxxx) (please complete the following information):**
 - AAWireless-A1h3fbRt

**Car (please complete the following information):**
 - Volvo XC60 (2018)

**Headunit (please complete the following information):**
 - Volvo Sensus

**Smartphone (please complete the following information):**
 - Device: OnePlus 8 Pro
 - Android version: 12

**Additional context**

Please also create a bug report from the help and support section in the companion app.

**Comment by Asghan86** [comment]
Can confirm the same for Focus ST with Sync 3 system and Pixel 5 with Android 13.

**Comment by Jon8RFC** [comment]
I get random dropouts/stuttering on non-streamed music. It's not regular, but happens enough that it wasn't a one-time thing.
Pixel 7 pro
2018 hyundai sonata limited (navigation head unit)

**Comment by Asghan86** [comment]
Any update regarding this from the Devs? Because this is really annoying!

**Comment by eskeff** [comment]
i have the same problem with s10+ and mylink 2 gm

**Comment by Asghan86** [comment]
No reaction from the devs up to now for nearly 4 months :(

**Comment by Asghan86** [comment]
Support said to post it here...

**Comment by Asghan86** [comment]
eMail is out, lets see if they can help this time.
Last year they said "to raise an issue in Github", let's see if the same answer is coming again.
