### ISSUE TITLE
2021 Honda Pilot only works in pass thru mode

### ISSUE THREAD

**Issue by Tim-303** [cpebit/aawireless-issues#174]
I can only get it to work in pass thru mode.  I have tried all the different options but nothing works.  When mot in pass thru the head unit hangs starting up.

**Comment by Snirpo** [comment]
Please enable the "GM fix" from the settings and it will work without passthrough.

**Comment by Tim-303** [comment]
Thank You.  I tried that before but it worked this time.Sent via the Samsung Galaxy S10 5G, an AT&T 5G smartphone
-------- Original message --------From: Chiel Prins ***@***.***> Date: 10/15/22  11:31 PM  (GMT-07:00) To: cpebit/aawireless-issues ***@***.***> Cc: Tim-303 ***@***.***>, Author ***@***.***> Subject: Re: [cpebit/aawireless-issues] 2021 Honda Pilot only works in pass thru mode (Issue #174) 
Please enable the "GM fix" from the settings and it will work without passthrough.
