### ISSUE TITLE
AAWireless 2.1.0 connection issues on 2019 Ram with Uconnect4

### ISSUE THREAD

**Issue by Tragic0428** [cpebit/aawireless-issues#177]
**Describe the bug**
A clear and concise description of what the bug is:

2019 Ram 1500 with 12" Uconnect4 screen; purchased the AAW adapter on 10/27 and installed it shortly after with no issues. Been running it near-flawlessly for a few days; on occasion it would give the "device not recognized" error, but would reset immediately if unplugged and plugged back in. 2 days ago when entering the vehicle it ceased to connect and will not reconnect.  I'm not sure what version of AAW I started out on or if there's been an update in the last few days, but something has to have changed. Through digging around, I see mention of folks switching to "MTP" to get it working again, but nothing in that menu has worked. When it first started with the issues 2 days ago, it would connect and bring up AA for about 5 seconds and then throw up the error. I'd disconnect from USB and reconnect and it would last another few seconds, then give me an error and refuse to connect again. Now it does not even make it that for, just continual "device not recognized" errors. Today when getting into the vehicle, I tried "forgetting" the device in the HU but that did not work.

I'm new to GitHub, but can provide screens and additional information if necessary.

**Screenshots**

**Device name (AAWireless/AndroidAuto-AAWxxxxxxx) (please complete the following information):**
 - Manufacturer + type
AAWireless-ziKx28VT

**Car 
 2019 Ram 1500

**Headunit:**
 - Uconnect4

**Smartphone:**
 - Device: Samsung Galaxy S22 Ultra
 - Android version 13

I've also tried a different known-working USB-A to USB-C cable to no success. I'll also submit a bug report in the app.

**Additional context**

Please also create a bug report from the help and support section in the companion app.

**Comment by Tragic0428** [comment]
Having trouble with the bug report; it seems like my phone is having intermittent connection with the dongle. It will start the logging process/download of report, but 3x it was unable to complete it. I'll try again later after work.

**Comment by Tragic0428** [comment]
Tried a factory reset, and noticed the name of the unit in the app changed names. According to the changelog for 2.1 this isn't supposed to happen?

**Comment by Snirpo** [comment]
Definitely not indeed. On 2.1.0 it's based on the serial name of the device. Based on all odd behavior you're experiencing it could be defective.

**Comment by Tragic0428** [comment]
Currently "b87235af".

First time pulling up the app today, looks like the interface has updated. Wonder if I got caught in the middle of an update?

**Comment by Tragic0428** [comment]
So fiddling with it today, I noticed that it seemed as if the phone and dongle were in some sort of connection loop. The status bar of my phone was constantly aflurry every few seconds notifying me of connections to AA/the wireless network. The head unit itself was still on the loop of "device not supported" notifications. I could alter and save in-app settings if I was quick. The AAW unit would display alternately blinking green, to white for a short period, to solid green for another short period, then back to blinking green LED. I plugged the dongle into the USB of my computer as was suggested in the FAQ for connectivity issues when trying to save settings, and it connected with a blinking blue LED for a few cycles, then would cycle to blinking green for a few seconds, then red and start all over.

In this vehicle, there are 4 USB ports in the front center console connected to the HU for data--2 USB A and 2 USB C. Using any of them for wired AA or charging seems to work fine. But reading on forums it seems that these ports can be problematic with all sorts of gremlins. Experimenting with the rear vehicular USB ports(no data/HU connection) the dongle seems to perform the same as with my laptop.

Replacement USB ports seem to run about $40. If my local dealer doesn't have one in stock I'm going to order one and replace it, unless the behavior exhibited when plugged into my laptop and the rear USBs also seems abnormal to someone more familiar with the dongle. Any thoughts?

**Comment by Snirpo** [comment]
Seems it's completely restarting in the car. On the laptop it will do the blinking blue --> 10 sec --> blinking green because it's in passthrough mode. Android Auto will time out on the phone side and restart the connection. On back USB ports, the behavior is indeed the same as on the laptop because there is no data connection. I suggest completely resetting the device by pressing the pinhole button once, clear bluetooth devices, clear Android Auto cache and data and try to set it up again. If the behavior stays the same, there's a good chance it's defective.

**Comment by Tragic0428** [comment]
Just getting back to this; just received and swapped it out with a new Mopar usb hub and still no dice. My wife's car, a 2020 Kia Sorento, doesn't acknowledge it either. I'll try to reset it all later today.

**Comment by Tragic0428** [comment]
Tried the reset, still the same behavior. I did get a "new" error message, but same conclusion.
![20221204_083002](https://user-images.githubusercontent.com/118329241/205493351-18c62e52-99b5-48c0-b4a2-ffef69ecb168.jpg)

As I sit in the car, the phone keeps connecting and disconnecting to the wifi, notifying me that android auto is available and then disconnecting again.

**Comment by Snirpo** [comment]
Good chance it's just defective if the Kia also doesn't see the dongle. In the Kia it should definitely just work. Please contact support@aawireless.io for a replacement.
