### ISSUE TITLE
Peugeot new 2008 multimedia system contnuos crash at the engine start after last update (2.1).

### ISSUE THREAD

**Issue by Pompiere73** [cpebit/aawireless-issues#178]
**Describe the bug**
After las update (ver2.1), at the startup of the engine, the entertainmen and info system crash, resulting in a freezing of all the systems, that in this car  are all controlled by the infotaiment.
To fix it, need to disconect the AAW, stop the engine, wait for 3 to 4 minuts to let all the apparatous shooting down, than, start again the engine and waiting for the system loading. 

**Screenshots**
If applicable, add screenshots to help explain 

AAWIRELESS 
 - Manufacturer + type

**Car (please complete the following information):**
 - PEUGEOT NEW 2008 active  (2020)

**Headunit (please complete the following information):**
 - Manufacturer(??) + type: 7"

**Smartphone (please complete the following information):**
 - Device: SAMSUNG GALAXY S10 LITE
 - Android version [12]

**Additional context**

Please also create a bug report from the help and support section in the companion app.

**Comment by Snirpo** [comment]
Please post the name of the device "AAWireless-xxxx or AndroidAuto-AAWxxxxx"

**Comment by Pompiere73** [comment]
The device is: *AAWireless-AcVwRigF*

*Tnx*

Franco G. da dispositivo mobile

Il Sab 19 Nov 2022, 15:42 Chiel Prins ***@***.***> ha scritto:

**Comment by Snirpo** [comment]
I enabled a custom firmware for your device, can you verify if this resolves the issue?

**Comment by Pompiere73** [comment]
Yes for sure, tnx!

⁣Franco Garavaglia da dispositivo mobile

Ottieni BlueMail per Android ​

Il giorno 23 Nov 2022, 21:03, alle ore 21:03, Chiel Prins ***@***.***> ha scritto:

**Comment by Pompiere73** [comment]
Well, i'm using it, and let let me say that is working properly!! Well done!
 It looks like the connection starts quitely delayed than before without any interferences with the car systems.
Really tnx!!

**Comment by Pompiere73** [comment]
Well, from more tests i can tell u that this firmware works properly for
this issue, but, now i noticed that with the music apps (spotify, deezer,
prime music) till i don't unlock the screensaver of the mobile (the mobile
is just unlock with smart unlock, but screen shooted down), the apps don't
work, responding with the message: "connection lost" or " no connection".
As soon as i turn on (just for a second) the screen of the mobile the apps
start to work (they find the connection?).

Tnx and regards

Franco G. da dispositivo mobile

Il Mer 23 Nov 2022, 21:03 Chiel Prins ***@***.***> ha scritto:
