### ISSUE TITLE
WAZE GPS stops working

### ISSUE THREAD

**Issue by sonny486** [cpebit/aawireless-issues#179]
WAZE GPS stops working after a few minutes.  Google Maps works fine.  WAZE GPS works fine on direct connection to car via USB on the phone. 

2018 Ford Expedition

**Comment by Snirpo** [comment]
Can you tell me what phone you have? Can you verify if the problem does not exist in passthrough mode?

**Comment by myhrmans** [comment]
Same issue here. Device does not reconnect until a power reset has happened.

**Comment by sonny486** [comment]
This happens with my pixel 6 pro and pixel 7 pro.

I will try passthrough mode and report back.

**Comment by Asghan86** [comment]
> Edit:
> Has enabled passthrough and will report back in a few days.

And? Did Passthrough solve it?

**Comment by myhrmans** [comment]
> @myhrmans 
> And? Did Passthrough solve it?

For me it helped. Forgot to get back.

**Comment by Claudio2108** [comment]
Sc7dste ragazzi. Ho lo stesso problema. Inoltre non riesco nemne
