### ISSUE TITLE
Notifications stay on map

### ISSUE THREAD

**Issue by Kazoobers** [cpebit/aawireless-issues#180]
**Describe the bug**Notifications such as red light camera show up once and then stay on the screen and we'll not disappear like normal. This prevents any new notifications of red light cameras showing up.

**Screenshots**

**Device name (AAWireless/AndroidAuto-AAWxxxxxxx) (please complete the following information):**
 - Manufacturer + type

AA Wireless 

**Car (please complete the following information):**
 - Manufacturer + type

2021 Toyota RAV4 PRIME 

**Headunit (please complete the following information):**
 - Manufacturer + type

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung Galaxy S10]
 - Android version [e.g. 10]
Samsung S21 ULTRA 

**Additional context**

Please also create a bug report from the help and support section in the companion app.

**Comment by Goldflame09** [comment]
Is this while using waze? If so, I've seen this across android auto regardless of this wireless adapter or not. I believe it to be a waze issue.

**Comment by Kazoobers** [comment]
Yes it is using Waze. I went to a Waze group and I guess it is a known issue and a bug report was submitted.

**Comment by Snirpo** [comment]
Yeah most definitely not an AAWireless issue. Closing it if you don't mind.
