### ISSUE TITLE
Music lag

### ISSUE THREAD

**Issue by justZanna** [cpebit/aawireless-issues#183]
**Describe the bug**
After the last update (2.1.0) and after a few minutes that the machine was started the music on Spotify begins to lag or skip for several seconds about each song. Playing music without Android Auto but only with bluetooth connection to the car does not present this problem

**Screenshots**

**Device name (AAWireless/AndroidAuto-AAWxxxxxxx) (please complete the following information):**
 - AndroidAuto-AAWdae1c506

**Car (please complete the following information):**
 - Kia XCeed (2021)

**Headunit (please complete the following information):**
 - Manufacturer + type

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S10e
 - Android version: 12

**Additional context**

Please also create a bug report from the help and support section in the companion app.

**Comment by serhio107** [comment]
Do you still experience the same problem?

**Comment by justZanna** [comment]
I resolved the problem by reset the device and re-configured it. At the moment, after two weeks, the problem did not recur
