### ISSUE TITLE
Full screen fix for Gen6 Subaru Outbacks.

### ISSUE THREAD

**Issue by aeloros** [cpebit/aawireless-issues#187]
Subaru Outback head units support full screen for Apple CarPlay, but not Android Auto currently.  At least one other Android Auto wired -> wireless device seems to have figured out how to make full screen work on 2020 Subaru Outback (Ottocast U2-Plus AI Box).  It would be awesome if AAWireless could provide this support as well.

**Comment by Snirpo** [comment]
That's because the Ottocast does AA over the CarPlay protocol. Not supporting widescreen in AA is a limitation of the head unit. We are currently making CarPlay possible on AAWireless including AA over CP as well. So we are already working on it :)

**Comment by aeloros** [comment]
Thank you for the explanation!  Any sort of rough eta on when that feature will be available?

**Comment by aeloros** [comment]
oh, and is there an issue I can keep an eye on that will be closed once the feature is available? :)

**Comment by Snirpo** [comment]
it's already available in beta. If you want, you can join us at https://join.slack.com/t/aawireless/shared_invite/zt-1ow5mpkjb-nFAWfVW~wTGJEgpSLZLfXA . If you send me a PM (Chiel Prins) I'll add you to our beta testers channel.

**Comment by aeloros** [comment]
Sweet, thanks!  Done!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
