### ISSUE TITLE
Dongle upgrade fails with Lookout VPN running

### ISSUE THREAD

**Issue by markm4663** [cpebit/aawireless-issues#194]
**Describe the bug**
When attempting to upgrade my dongle 2.0.0 to 2.1.0, the upgrade fails immediately if Lookout VPN is enabled on my phone.  When I disable the Lookout VPN, the upgrade completes successfully.

**Screenshots**
None

**Device name 
AAW2LqyKGIU 

**Car (please complete the following information):**
 2021 Toyota Highlander Premium

**Headunit (please complete the following information):**
 Factory installed Premium Audio system

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S22+
 - Android version 13

**Additional context**
No additional information

Please also create a bug report from the help and support section in the companion app.

**Comment by Sergiu-Dobre** [comment]
Yes, that is correct, please make sure to whitelist Android Auto and AAWireless app in your VPN settings.

**Comment by markm4663** [comment]
I did not have the ability to manage a whitelist.  The VPN is managed by Lookout.  My only option at this time is to disable the feature in Lookout that titties my data through the Lookout VPN.  I will continue to disable there option to use the Lookout VPN when attempting to update my dongle.

**Comment by markm4663** [comment]
Sergiu,I sent the same information about the upgrade issue to Lookout.Here is they're response:"Hi Markm4663,Thanks for reporting this to us. I've created a trouble ticket for our engineering team to review. I can't provide an ETA, but if we can get this fixed, we'll update the app. Thanks for using Lookout!"Hopefully, they will be able to resolve the issue.Just in case, could your provide the details on what exact stores need to be whitelisted in the VPN.  URL, port number and whatever you think Lookout might need?Thanks again,Mark
-------- Original message --------From: Sergiu Dobre ***@***.***> Date: 4/6/23  2:50 AM  (GMT-07:00) To: cpebit/aawireless-issues ***@***.***> Cc: markm4663 ***@***.***>, Author ***@***.***> Subject: Re: [cpebit/aawireless-issues] Dongle upgrade fails with Lookout VPN running (Issue #194) 
Yes, that is correct, please make sure to whitelist Android Auto and AAWireless app in your VPN settings.
