### ISSUE TITLE
Media sink does not work (as expected?)

### ISSUE THREAD

**Issue by sdoeringNew** [cpebit/aawireless-issues#195]
I happily noticed the Media sink option in the AAWireless Android App.
I've activated it, because I want to use Android Auto which is aawirelessly connected to my phone. And my daughter want's to Bluetooth-connect her tablet to hear her Spotify over the car's stereo (head unit).

The Media sink "enables media playback via another Bluetooth device". Perfect. Just my use case.

However Android Auto (or AAWireless) kills every attempt to connect a different Bluetooth device to the head unit.
I can connect the tablet to the head unit successfully. A second later AAWireless spawns in the Bluetooth list, connects itself to the head unit and removes any connected Bluetooth device - except my phone - from the head unit.

Did I missunderstand the Media sink option?
How can I achieve my wish?

----

Android Auto uses Bluetooth for calls. Even removing the permissions to Calls, Call list, Contacts and Microphone doesn't solve the issue.

**Comment by Snirpo** [comment]
Unfortunately that's not what this option does. We probably should improve the description.

What this option does is disable media audio output through the Android Auto protocol (via wifi and eventually usb). This means you can route phone audio, while running Android Auto, through phone speakers or for example a paired Bluetooth audio device (head phones, external amplifier).

If I understand correctly, you want to have another device providing audio (music) to the car, while using Android Audio. Most head units block Bluetooth audio (a2dp) while using Android Audio / CarPlay. So I'm afraid what you want is not possible.
