### ISSUE TITLE
In normal mode (non-passthrough) the dpi is not default

### ISSUE THREAD

**Issue by Snirpo** [cpebit/aawireless-issues#40]
The default dpi seems much higher than when connected via USB. I've now changed it to 144 which seems roughly the same. With the default I would guess it's above 160. My head unit is a stock Suzuki SLDA.

**Comment by borconi** [comment]
Could be something with the proto file... where we miss something and when we save the message we inadvertently brake an unknown field...

**Comment by Snirpo** [comment]
This likely has something to do with packed repeated fields.

**Comment by borconi** [comment]
Also left/right issue, probably to be solved by version 1.2.0 with fixed protobuf

**Comment by TcT2k** [comment]
I'm one of the people reporting this issue initially. The head unit is Suzuki Jimny (Bosch SLDA).

I've updated my unit to 1.2.0 and it still only displays the correct dpi in passthrough mode.
It seems to me that it's correct in the Y axis and there is only a difference in width (I'm not sure if it was the same with 1.0.0).
I could provide pictures (if that's helpful at all)  or could the "bug report" feature be helpful?

For my head unit it's not a big issue as the the dpi isn't far off, but that could be different on higher resolution head units.

**Comment by Snirpo** [comment]
I expected 1.2.0 to fix it. I think we need some experimenting with this. Do you mind testing beta testing?

**Comment by TcT2k** [comment]
If there is not a big chance of bricking the device I wouldn't mind some beta testing.

**Comment by TcT2k** [comment]
Just tow pictures to show the issue (sorry for bad quality but it was sunny).
I've added the red line to make the difference relative to the sdcard slot above the display more obvious.

Without passthrough:
![image](https://user-images.githubusercontent.com/5075894/115679457-e506b580-a352-11eb-892e-eaf0731ac2ca.png)

With passthrough:
![image](https://user-images.githubusercontent.com/5075894/115679584-07003800-a353-11eb-9cf6-6ec61157c25a.png)

**Comment by Snirpo** [comment]
@TcT2k is this still an issue with firmware 1.4.0?

**Comment by TcT2k** [comment]
> @TcT2k is this still an issue with firmware 1.4.0?

Just tried with 1.4.0. Disabled passthrough and still uses the wrong DPI as described before.

**Comment by TcT2k** [comment]
@Snirpo just tested 1.5.0 and it now works without passthrough enabled

**Comment by Snirpo** [comment]
Surprising, cause we didn't change anything in this regard :/
