### ISSUE TITLE
Day/Night auto toggle (same as in Google Maps e.g navigating in night/in tunnels etc)

### ISSUE THREAD

**Issue by Borssie** [cpebit/aawireless-issues#49]
Hi developers,

Would it be possible to let AAWireless decide when Android Auto is going from day view to night view, e.g when it becomes dark/in tunnels? 

The Android Auto on my phone (standalone) does this properly but when my phone is connected to my head unit doesn't work with that. I also don't have automatic headlights. Hope it is possible to make this happen.

Thanks/ Bedankt

Regards Jeroen (Borssie)

**Comment by Snirpo** [comment]
It's possible from the Android Auto developer settings to force day / night mode or make the phone / car device.
