### ISSUE TITLE
OTA update problem: (Galaxy Z Fold 2)

### ISSUE THREAD

**Issue by igorstefus** [cpebit/aawireless-issues#55]
Hi

It looks like OTA update is not working well on some phones or some android versions. My device is from second batch  sent to Germany for distribution so it shoud have DRAM patch already applied. I have Samsung Galaxy Z Fold 2, app version is 1.71 and for me OTA update 1.2.3 was constantly failing with message "can not connect to the device". My phone is running android  11. 

I manage to do update by using my old Samsung Note 8.

**Comment by Snirpo** [comment]
Are you running a VPN?

**Comment by igorstefus** [comment]
Nope. I have VPN client on my phone but it was not running when I was trying to update.

**Comment by Snirpo** [comment]
Ok, i'll look into it. Not sure why it's works on one and not the other.

**Comment by Snirpo** [comment]
@igorstefus Is this fixed for you on app version 1.9.3?

**Comment by igorstefus** [comment]
Yes. Connection is much better now. Telephone was overhitting when I first manage to connect it but now it is much better. Thanks!

**Comment by Snirpo** [comment]
Ok, closing this issue :)
