### ISSUE TITLE
Listen to navi instructions on BT headset while car music playing on car loudspeakers

### ISSUE THREAD

**Issue by martinarmstrong123** [cpebit/aawireless-issues#59]
Car: 2017 Audi A4

Headunit: MMI plus (MIB2?)

Smartphone: ASUS Zenfone 6 with Android 11 (or Motorola one with android 10)

The desired scenario is as follows and cannot be achieved even with the AAWireless option 'disable audio sink' switched on:

The driver is using a navigation app on the mobile phone and wants to hear the turn-by-turn navigation commands on a bluetooth headset connected to the phone.
The front seat passenger is playing music from the car stereo system on the car loudspeakers and wants uninterrupted listening pleasure.

Further explanation:

Under normal circumstances with Google Maps it is not possible because the turn-by-turn navigation commands are always output on the car speakers and interrupt any car music playing on them.

With the present AAWireless option 'disable audio sink' switched on:

With a music app on the phone when it is playing music, this music is retained on the phone and can be listened to via the phone speakers or with a headset attached to the phone and is not sent to the car speakers BUT any music that is generated by the car stereo system is halted and only restarted when the music app is paused.

With Tomtom(with output on media channel selected), Google Maps, and Waze the option has no effect on what happens and the turn-by-turn navigation instructions still come on the car loudspeakers. The output from these apps seems to be handled differently (perhaps due to different audio attributes) even though with Tomtom at least the output is supposedly also on the media channel as it is for music apps. Emil says, however, that the output occurs on a speech channel.

Suggestions for implementing the feature request to retain the navigation app audio on the phone in order of preference:

1. It would be preferable to me if the option would just work on the standard output channel for navigation instructions, as that would enable me to use it with TomTom or Google Maps, because I sometimes use Google Maps when a car passenger sends me a destination that they have found in Google Maps. Also all other output eg. audio for messaging, would then presumably come to the car microphone/loudspeakers as at present. 
2. If it worked for all output, even though in Emil's opinion AA would then not work at all, then that would be just as good because then the messaging audio also would come on the bluetooth headset and presumably the verbal answers would be received by google via the headset microphone, hopefully making google better at understanding what I have said.
3. If it was just done for the voice call channel that would only enable its use with Tomtom which is the only navigation app which allows the output channel to be selected but with this setting the volume of the headset is more complicated to control

My workarounds for the problem:

An existing partial workaround is as follows:

With Tomtom the output channel for the turn-by-turn instructions can be chosen from the following: media, voice call, system, notification, alarm and ring. I find that the voice call channel is the best and with this the audio is retained on the phone and can also be listened to on a headset. 
Drawbacks:
1. there is not such a fine control of the volume which is critical when adjusting a comfortable volume for a headset.
2. It may be that if I receive a phone call while in the car the 2 audio outputs could interfere with each other. 
2. Any music from the car on the car speakers is muted when turn-by-turn instructions are output to the headset by the tomtom app.

The only complete workaround is to use 2 phones running the same version of Tomtom with the identical destination input, one providing me with the navigation instructions on a phone headset and the other connected to AA providing the map on the car screen with the navigation instructions muted. This solution does work but it is sub-optimal!! It also ideally needs both phones to have a simcard in them to receive traffic information.

Note for anyone reading this: I live in Germany where using a headset in a car is perfectly legal!

My device-id is AAWireless-SdZWzjpS if you ever wanted to send me a test version.

**Comment by martinarmstrong123** [comment]
@Snirpo 
Any idea when you are likely to have the time to look at ways to give me the feature that I would like? I noticed in the comments a Noah McClair asked for a similar change to the audio sink option 8 hours ago.

**Comment by Snirpo** [comment]
We are still in progress fixing / improving the basic functionality. As soon as we have the start / stop functionality spot on we can look into new features. I think it's relatively easy to implement.

**Comment by martinarmstrong123** [comment]
@Snirpo
If you think it is relatively easy to implement then perhaps you will be motivated to make my request the first one you tackle as a pleasant relief from the hassle of solving problems so that you can quickly reduce your 'to do' list by one item!
It would be good to have it for when I drive on a long trip this summer!

**Comment by dantheman80** [comment]
@Snirpo 
Any luck with this? i think a bigger and growing market of people are requesting this.
Considering your comment of being "relatively easy" it would be great to have this and to stop people from constantly asking for an update of when this will be complete....
right now i and others have to sacrifice google assistant and Waze/GM for better quality music.
Any possibility of have this project request actioned?

**Comment by martinarmstrong123** [comment]
@Snirpo
following my terrible experience with google assistant lately, I think that I would prefer it also to run via my bluetooth headset in addition to the navigation commands, as requested by someone else here (#84 in this list of requests) and not via my car audio. Maybe then I could possibly get myself better understood as the microphone would be next to me and I would not have to shout in the car, hoping I was doing it somewhere near the microphone, not knowing where exactly it is positioned.
I hope that an attempt to realize my extra functionality request will be one of the extra surprises mentioned in the new year indiegogo update!

**Comment by martinarmstrong123** [comment]
@Snirpo
As the time you can spend on new feature requests is obviously severely limited, a minimum solution to my problem would be that when Tomtom sends navigation commands on the voice call channel and they come on the bluetooth headset, if you could simply block the information coming from the phone to the car telling it that it is receiving the commands, then the car music would carry on regardless.
I would be willing to pay extra for this option.

**Comment by Snirpo** [comment]
Added to project, we will try to pick this up in 2.x
