### ISSUE TITLE
After phone call, podcast/music switches to phone speaker

### ISSUE THREAD

**Issue by mfonville** [cpebit/aawireless-issues#61]
**Describe the bug**
Since the 1.2.0 update I have the issue that after a phone call, the music/podcast that was playing before switches to the phone speaker. If I disconnect AAW and plug it back in again, it works properly again.

**Car (please complete the following information):**
 - Renault Zoe ZE 50 (new generation december 2019)

**Headunit (please complete the following information):**
 - Renault Easylink

**Smartphone (please complete the following information):**
 - Device: Mi 11 (venus)
 - Android version 11, MIUI Global 12.5.1

**Comment by Snirpo** [comment]
@mfonville Should be fixed in 1.4.0, can you verify?

**Comment by mfonville** [comment]
I will test and confirm it as soon as I have made phone call in the car

**Comment by mfonville** [comment]
Unfortunately it is not resolved :-(

**Comment by mfonville** [comment]
Not sure if it is related, but since 1.4.0 sometimes my phone doesn't connect Bluetooth to the head unit. E.g. at those moments I cannot have phone calls with the car's head unit :-/

**Comment by Snirpo** [comment]
Small update: will be fixed most likely with the new revised start / stop functionality in app 1.10.x, where we will not use Bluetooth anymore for starting up AA.

**Comment by mfonville** [comment]
Alright! Any ETA when this update arrives?

(btw, my problem occurs without using start/stop feature enabled, not sure if matters)

**Comment by Snirpo** [comment]
Might by fixed by switching to dongle logic in AA https://github.com/cpebit/aawireless-private/issues/11

**Comment by mfonville** [comment]
That repo is private.
Is there anything I should do to enable that logic?

**Comment by Snirpo** [comment]
Sorry, probably should have been more clear. We will release this in 2.0 of the firmware, in about 2-3 weeks.

**Comment by mfonville** [comment]
FYI even though the firmware 2.0 is not yet released (at least not to me as a regular user) the issue seems to be resolved when my Mi11 received an upgrade to MIUI 13
