### ISSUE TITLE
Is there a way to reset USB data through companion app?

### ISSUE THREAD

**Issue by ZoltanAndras** [cpebit/aawireless-issues#63]
A manual button would be nice. When this happens, there are AA logos on top of the phone display but the AA logo is not on the headunit, hence the automatic attempt is not made at all. Please bear in mind that this only happens if AA connection is lost during driving (like passing through some guys illegal 2.4/5ghz phone signal or directional antenna) or if you get out of the car and come back, or do a remote engine start where your phone is partially far away from the car, messing up with bt and wifi connections. (enabling start/stop in companion app does not help because many times the bt connection to headunit is already there, but wifi was not connected at that moment so the companion app tries/fails/does not seem to try again as BT was always connected, there could be different ranges as BT is 2.4ghz but wifi could be 5ghz)
At that point of failure turning off blueooth and back on (manually or via tasker) or better/faster yet unplugging-plugging back AAwireless fixes it. If a manual button is available in the companion app, like a "reset usb" and/or "reestablish AA" it might be helpful.

**Comment by Snirpo** [comment]
It should automatically revive the connection, if not we have to fix it in
another way than a manual button.
