### ISSUE TITLE
AAWireless now works fine except when wearing my smartwatch.

### ISSUE THREAD

**Issue by ZoltanAndras** [cpebit/aawireless-issues#65]
When smartwatch is on AAWireless tries to pair but will not connect. LED light turns red. After a few seconds it turns blinking green and then again red and doesn't connect until I disconnect smartwatch and will connect. I have tried several times. Works fine as long as Smartwatch is off. Head unit will pair to Honda handsfree link and AAWireless as long as Smartwatch is not on.
Any thing else I can try?

**Comment by Snirpo** [comment]
Will most likely be fixed by using the dongle logic in AA. https://github.com/cpebit/aawireless-private/issues/11
