### ISSUE TITLE
Audi MMI freezes recurrently every 30 to 60 seconds

### ISSUE THREAD

**Issue by FSeidinger** [cpebit/aawireless-issues#66]
# Bug description

The Android Auto application freezes recurrently round about every 30 seconds. After being frozen the app functions for another 30 to 60 seconds.

# Screenshots
I've recorded a video that show the effect. While the video was recorded I constantly turn the jog wheel of my car to better show the effect. I've linked the video from my Google Drive -> [Video](https://drive.google.com/file/d/1fASuFZEwzhVsK4cFCPbwQTd8rNZa4i7e/view?usp=sharing)

# Car
I use an Audi A4 station wagon round about four years old.

# Headunit
I cannot say for sure, but it is the highest option of in car MMI. I can try to find out if needed.

# Smartphone
My Phone is a Huawei 20 Pro[](url)

**Comment by Snirpo** [comment]
Do you have another phone to test with? In general Huawei phones are one of the most problematic with Android Auto (wireless).

**Comment by FSeidinger** [comment]
> Do you have another phone to test with? In general Huawei phones are one of the most problematic with Android Auto (wireless).

Unfortunately not. This is my one and only. It's for business and private use.

**Comment by MaTyyyJ** [comment]
Same issue for me - OnePlus 8T and A4 B9. But for me freezes for 3-5 seconds.

**Comment by Snirpo** [comment]
Will check (somehow).

**Comment by FSeidinger** [comment]
I've updated to firmware 2.0.0 and witched to client mode using my car's hotspot. I could not notice the freezing since that anymore.
