### ISSUE TITLE
Audio dropouts

### ISSUE THREAD

**Issue by k-a-s-c-h** [cpebit/aawireless-issues#70]
**Describe the bug**
I have audio dropouts every now and then, it only helps to restart the smartphone. When I connect the smartphone with the cable without the AAwireless I do not have these problems.

**Screenshots**

**Car (please complete the following information):**
 - Opel Insignia Grand Sport
 
**Headunit (please complete the following information):**
 - Opel Navi900 IntelliLink 2. Generation

**Smartphone (please complete the following information):**
 - Device: OnePlus 8 Pro
 - Android version 11

**Additional context**

**Comment by wreyniers** [comment]
I have audio dropouts constantly as well. Some days it works ok with minimal dropouts, other days it's so bad I go wired. Very unpredictable. 

Also as of late I'm getting a glitch where the audio will start/stop continuously until the music is paused from Spotify (or whichever app I'm using), wait 15 seconds than restart. This seems new since 1.4 and 1.5.

Device: Pixel 5
Car: 2020 Subaru Ascent

**Comment by Snirpo** [comment]
I can put your device back on 1.3.0 for a test?

**Comment by k-a-s-c-h** [comment]
I can not go back unfortunately, with me goes only since 1.5.0 or 1.4.0 AAwireless with an Infotaiment system in my Opel.

**Comment by wreyniers** [comment]
I'd like to give it a try @Snirpo - how do I go about it?

**Comment by Snirpo** [comment]
If you pass me your device name (AAWireless-xxxxx), I'll put it back on 1.3.

**Comment by wreyniers** [comment]
@Snirpo my device is `AAWireless-ObK7unVu`

Thank you!

**Comment by Snirpo** [comment]
@wreyniers You're back on 1.3.

**Comment by wreyniers** [comment]
I have to run the update from my end though right?

**Comment by Snirpo** [comment]
Yes :) you can update (downgrade) through the app.

**Comment by k-a-s-c-h** [comment]
@Snirpo has been rebuilt something from version 1.4.0 because you asked about version 1.3.0?

**Comment by Snirpo** [comment]
Sorry I don't quite understand what you mean.

**Comment by k-a-s-c-h** [comment]
was something changed in the sound processing in version 1.4.0? Because we should test it with version 1.3.0?

**Comment by Snirpo** [comment]
Oh no, @wreyniers indicated he got issues since 1.4, hence putting him back to 1.3. Actually I expect there to be no difference at all between 1.3, 1.4 or 1.5. The differences are very minor between these versions.

**Comment by wreyniers** [comment]
@snirpo, have only done two short trips and things didn't go haywire. I'll update you in a couple of days to see how 1.3 holds up.

The start/stop/start....bug was something brand new on 1.4. 

I did see this on the AA community: https://support.google.com/androidauto/thread/111480702/music-audio-becomes-choppy-in-aa-using-wifi-when-switching-to-any-other-app-while-playing

**Comment by wreyniers** [comment]
I've done quite a bit of driving back on 1.3 now and I'm confident referring resolved the start/stop stutter in the audio feed.  Tim mentioned not a lot was changed in 1.4 and then a lot was referred in 1.5. Still though, in my setup there seems to be something that breaks in these two releases. I'm going on a road trip here in a bit so I want to cable this more stable release for another week or so. If be happy to jump back forward to see if the stutter indeed does chime back.

**Comment by wreyniers** [comment]
It should be noted I still get the occasional audio blips. Some drives there are no blips, some drives they happen every 3 to 30 seconds.

**Comment by Snirpo** [comment]
Changing to dongle https://github.com/cpebit/aawireless-private/issues/11 logic seems to fix this issue for some GM cars. I'll close this issue for now and we will monitor it. Version 2.0 of the firmware will contain this logic.

**Comment by Nedlinin** [comment]
> It should be noted I still get the occasional audio blips. Some drives there are no blips, some drives they happen every 3 to 30 seconds.

@Snirpo : Is the 2.0 firmware expected to fix these audio dropouts? I recently purchased a Hyundai Ioniq 5 and noticed these dropouts.  They are seemingly random and happen every 5 seconds to 5 minutes and typically last maybe half a second.
