### ISSUE TITLE
AV glitches when parking 

### ISSUE THREAD

**Issue by MattHGR** [cpebit/aawireless-issues#72]
**Describe the bug**
At the end of a drive when I put my car into reverse, the parking sensor screen shows up and the parking sensors start beeping (normal operation). 
When this happens, AA starts to glitch. The screen runs at 1fps at best, and the music/audio is jumping around. 
If I try to use my phone screen, it is also experiencing similar issues. 

**Screenshots**
Can't screenshot lag. 

**Car (please complete the following information):**
 - 2019 VW polo

**Headunit (please complete the following information):**
 - VW MIB II (I think) 

**Smartphone (please complete the following information):**
 - Device: Samsung note 10+
 - Android version 11

**Additional context**
I am using pass through mode.
The VAG fix mode gives me other issues (will open on separate ticket)

**Comment by Snirpo** [comment]
Please post your device name AAWireless-xxxx. This issue doesn't happen when using with cable?

**Comment by MattHGR** [comment]
bHOIEvGQ
It's fine with the cable which is why its so odd.
I am driving a VW so I should probably be using the VAG fix feature. However, that brings up another issue (opened a separate ticket for that)

Thanks,
Matt

Matt Hargraves

________________________________

**Comment by Snirpo** [comment]
Your car doesn't have a Technisat HU, so the VAG fix will probably only cause issues indeed.

**Comment by MattHGR** [comment]
Yes. If I switch my phone screen on, the UI is extremely laggy.
If I disconnect AA Wireless, it is fine again

Just to reiterate, I am using pass through mode in this scenario. Therefore VAG fix is disabled right?

**Comment by Snirpo** [comment]
Correct, but the VAG fix will only cause issues in your case, it's only meant for Technisat HU's, where it's also auto-enabled.

**Comment by MattHGR** [comment]
This is great to know!

I will try non pass through mode with no VAG fix and let you know the results!

**Comment by MattHGR** [comment]
After further testing myself, the issue only happens with pass through mode enabled. It is fine when disabled.

Happy to help you troubleshoot further if you need. 
Though my fix is to just disable pass through mode!

**Comment by MattHGR** [comment]
OK it happened again today.
I had pass through disabled.

So the issue happens with pass through enabled and disabled. Very odd

**Comment by Snirpo** [comment]
I'll add it to our issue board, but this won't be an easy one without actually having the same car.
