### ISSUE TITLE
Announcement and music volume issue 

### ISSUE THREAD

**Issue by MattHGR** [cpebit/aawireless-issues#73]
**Describe the bug**
When using the VAG fix option, I get an issue with announcement and music volume. 
If my navigation app (gmaps or waze) says anything, my music volume is turned down. (normal operation) 
When the announcement finishes, the music volume stays down. Trying to adjust the volume using head unit or steering wheel controls, only changes the announcement volume. It seems to be stuck in announcement mode. 

**Screenshots**

**Car (please complete the following information):**
 - 2019 VW polo

**Headunit (please complete the following information):**
 - VW MIB II (I think) 

**Smartphone (please complete the following information):**
 - Device: Samsung note 10+
 - Android version 11

**Additional context**
Issue doesn't happen if I use pass through mode. But I get another issue when I use pass through mode :/

**Comment by Snirpo** [comment]
Does this issue also happen in non-passthrough mode without the VAG fix applied?

**Comment by MattHGR** [comment]
I will try this tomorrow.
Do I need to use the VAG fix in my car? I presumed from the start it would apply to me

**Comment by MattHGR** [comment]
With pass through and VAG fix both disabled, the issue is gone.
I had presumed I needed the VAG fix enabled because I was in a VAG car. Glad to see it is not required.
Happy to close this ticket 😊
