### ISSUE TITLE
Can't escape "searching for new device", after it fails. Have to force close app.

### ISSUE THREAD

**Issue by fryeguy100** [cpebit/aawireless-issues#76]
**Describe the bug**
If you open the AAwireless app and select "AAWireless device" > "Add New" > "Next" > "Next" to add a new device. You then can't escape that menu if it fails to find a new device. Users might be tempted to click through these menus when their AAwireless dongle fails to connect. They may try to re-add it using the steps above. But once it fails to find a new device (because you already added it), you can't go back or escape the menu. You have to force close the app to get back to the main page of the app.

**Screenshots**

**Car (please complete the following information):**
 - Nissan Sentra

**Headunit (please complete the following information):**
 - Nissan Connect

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Note 20 Ultra
 - Android version 11

**Additional context**

**Comment by Snirpo** [comment]
This is a bug, will be fixed in app 2.0.
