### ISSUE TITLE
Connect/Disconnect Feature

### ISSUE THREAD

**Issue by svd** [cpebit/aawireless-issues#77]
I'd like to request a feature to add for the app.

Could you please implement a button within the application to turn On/Off or force reconnect?
I would consider following use cases:

1. As an AA user I would like to fully disconnect AA device - same as I would do if I unplug the cable (not just switch to car UI).

2. As an AA user I would like to force reconnect. Sometimes, AA is not connected to my car (I've played with different timeout settings, but did not get stable behavior), thus I'd like to have quick and easy way to force reconnect. As of now, I use following workaround - I open settings, edit wifi connect  timeout and save - and I get it reconnected and working. But it takes time and makes me be less careful while driving :) I believe implementing use case 1 would also solve this one.

**Comment by Snirpo** [comment]
Is it possible, but only in start / stop mode where we control the starting / stopping of AA. Force stop is already added to this functionality for the next version of the app. I might also add a manual start / reconnect functionality. Have to check where to put it UI wise.
