### ISSUE TITLE
Within the app, allow user to set whether app should start up on boot.

### ISSUE THREAD

**Issue by lschapker** [cpebit/aawireless-issues#78]
Currently, I must install another app so that this new app can start AAWireless when I reboot my phone (which happens automatically twice a week).

If I do not manually start the AAWIreless after a reboot of my phone, when I enter my vehicle, my Android Auto does not connect to the head unit.  I must pull over (because of the delay it takes to connect to the head unit) and dittle my phone to start AAWireless.  After that, everything works as expected.

I understand that this is really a minor issue, yet it is frustrating.  I suspect that with the system permission "Startup on boot" and a little code within the app to allow the end user to select whether or not to do so, my user experience would be much better.  

Thank you!

**Comment by Snirpo** [comment]
Is this in start / stop mode?

**Comment by lschapker** [comment]
I can't tell right now.  I have to go out to the car to connect.
I don't think it is because the app dopes not have the "Startup on Reboot" app permission enabled.

**Comment by Snirpo** [comment]
Well, I'm asking, because when start / stop mode is not enabled, the AAWireless app doesn't control the startup of Android Auto. You can uninstall the app and it will still work. So if AA starts up when starting the AAWireless app with start / stop disabled, it's probably a side effect of the app connecting to the device via Bluetooth for synchronization purposes.

**Comment by lschapker** [comment]
Understood.  (I am not using "Start/Stop" because my USB port is not constantly powered)
How do you suggest I try to debug this?

**Comment by Snirpo** [comment]
Please first try: https://cpeb.freshdesk.com/support/solutions/articles/80000521901-device-never-connects-and-keeps-blinking-green
