### ISSUE TITLE
Add Wifi Signal Strength Feature

### ISSUE THREAD

**Issue by fa1c0n64** [cpebit/aawireless-issues#81]
I have a vehicle that keeps the power on for the USB ports.  I believe it eventually powers down after an hour or so.  I found that the Wifi, and possibly bluetooth, signals are fairly strong and will maintain connections even when my car is in the driveway and I am in the back of my house.  I know you have the auto start/stop which is fairly effective but can be slow and not always consistent.  It would be nice if we could adjust the wifi power setting since it only need enough strength to work within the vehicle.

I'm not familiar enough with the AA Wireless protocols to know if bluetooth would need similar power adjustments.  

I read some ideas in the XDA forums to test this and found that surrounding the device with tin foil serves a similar effect to reduce the signal strength which seems to work pretty well, but a cleaner programmatic option would be preferred.

**Comment by Asghan86** [comment]
Great idea.
Should be easy to implement, as it a default feature in nearly all WiFi routers e.g.
Please make the WiFi signal strength adjustable, even if it is just some easy steps like 100, 75, 50 and 25% or so.

**Comment by Snirpo** [comment]
Start / stop is the solution for this issue, so completely disabling the connection instead of lowering the signal.
