### ISSUE TITLE
Add a toggle within the app to enable AA for RHD vehicles.

### ISSUE THREAD

**Issue by RobotRoss** [cpebit/aawireless-issues#82]
As Android Auto has a mode for RHD cars, it'd be nice to have the ability to enable and disable this in AAwireless for head units which don't make use of the feature automatically.

Supposedly the head unit is meant to report whether the vehicle is LHD or RHD, but in the case of many vehicles this doesn't seem to happen, or in the case of aftermarket HUs this cannot happen (as the unit likely does not know, or does not care which side the driver is on).
Thanks!

**Comment by Snirpo** [comment]
Location of driver seat can now be forced from AA settings.
