### ISSUE TITLE
AAW device reset connection/crashes when mobile data reconnects

### ISSUE THREAD

**Issue by valerikolev65** [cpebit/aawireless-issues#83]
**Describe the bug**
In poor mobile coverage, when mobile data reconnects, AAW device resets connection, that causes AA to disapear and reappear on the HU within a few seconds.
Same happens in roaming when mobile connections switches from one operator to another

**Screenshots**
n/a
**Car (please complete the following information):**
 - VW Passat B8 2017

**Headunit (please complete the following information):**
 - Technisat MIB2

**Smartphone (please complete the following information):**
 - Xiaomi Mi11, xiaomi.eu weekly rom
 - Android version 11
 - AAW device - AAWireles-eztE821S 

**Additional context**
Wired connections works stable.

I think the issue appeared after AAW firmware update after 1.3.0.
Since then rom and AA were updated too.
So, not sure what update causes the issue.

Already tested all settings and xiaomi workarounds I have found.

Edit: Seems it is not AAW bug, but in my case MIUI 12.6, A11 bug, making short wifi disconnect. Today updated to xiaomi.eu A12 rom and this issue is gone. Will see and report if there are other bugs, related to AAW.

**Comment by stu5719** [comment]
I also had the same problem. AA freezes and there is no sound in the audio, then AA disappears, and AA reconnects within 15 seconds.
Screenshots
n/a

Car (please complete the following information):
Suzuki Swift Sport Hybrid 2020

Headunit (please complete the following information):
Original screen, wired AA

Smartphone (please complete the following information):
Oneplus 8 pro (Android 11)
AAW device-AAWireles-gOkLopuy (v1.7.0)

**Comment by stu5719** [comment]
When there is no sound from AA and the screen freezes, just before disconnection, turn on the Wi-Fi hotspot, and AA will be restored immediately.
I guess the Android system is trying to change the Wi-Fi connection because of the short switching base station and there is no Internet at the moment.

**Comment by Snirpo** [comment]
This is an XIaomi issue we unfortunaly cannot fix.

**Comment by 420pootang69** [comment]
Could we not have a warning that Xiomai devices don't work with AAwireless before purchasing such an expensive device and waiting months for delivery?
