### ISSUE TITLE
Almanac powered day/night mode for maps

### ISSUE THREAD

**Issue by osunick** [cpebit/aawireless-issues#85]
Automatic day/night mode for maps doesn’t work in my car because it’s a retrofit kit, I can switch to phone for day/night but it uses the active theme of the phone to determine what mode to put Android Auto Maps in, since I’m always using the dark theme to save power on my OLED phone, this won’t work. I would like to know if it’s possible for an option that just uses sunrise/sunset times for your location to change the map display.

**Comment by Snirpo** [comment]
You can force night mode from Android Auto developer settings.
