### ISSUE TITLE
AAWireless does not connect to headunit (Skoda Amundsen)

### ISSUE THREAD

**Issue by yawnsde** [cpebit/aawireless-issues#86]
**Describe the bug**
AAWireless device never connects to the headunit

**Car (please complete the following information):**
 - Skoda Superb III (3V), built 2016

**Headunit (please complete the following information):**
 - Skoda Amundsen (2016)

**Smartphone (please complete the following information):**
 - Device: Google Pixel 3a
 - Android version 11 (Security Update September 5th, 2021)

**Additional context**
My phone is working perfectly fine using an USB cable. Android Auto appears on screen, navigation, Spotify and such are working like a charm. Using the same cable to connect the AAWireless device does boot up the device. It starts blinking green, then blinks blue but never turns to solid blue. Setting the USB Mode in the companion app to "MTP with forced start" makes the light turn solid blue after some seconds and on the headunit I see "Reading USB1", but after that nothing happens. I tried different USB cables, but with no change and now I am a bit lost.
The AAWireless device is up to date, running 1.5.0, 
Edit: There is no firmware update available for the headunit

**Comment by SAS995** [comment]
If you using a vpn, pause it or close it.

**Comment by yawnsde** [comment]
> If you using a vpn, pause it or close it. On my mib 2.5 is working perfectly

Hi. I do not have any VPN service running, not even set up.
So you have the same headunit and it works for you? Would you mind sharing your settings in the companion app?
