### ISSUE TITLE
Sound quality 

### ISSUE THREAD

**Issue by SAS995** [cpebit/aawireless-issues#87]
Please add as a bypass I think, for the sound.
Sound should play separately via Bluetooth as phone calls, this way we will receive the best sound.
For the moment we have music sound same as with wired Android auto and that is bad. We need the wireless sound quality.
This is probably the best feature that you can add.
The ideea is somehow there as an audio sink in settings but I can't connect it to the head unit, only plays in the phone.

**Comment by SAS995** [comment]
No. If I use disable audio sink, music sound it is only in phone and not in head unit. 
Need to connect audio wireless. The sound is better via Bluetooth / wireless vs wired USB / aawireles device. 
This is what I'm trying to tell you.

**Comment by Snirpo** [comment]
Disabling audio sink is all we can do, rest is up to the phone and HU.
