### ISSUE TITLE
Block the Navigation active message to the HU

### ISSUE THREAD

**Issue by Pixel-Gavin** [cpebit/aawireless-issues#88]
If possible I'd like to see a feature/option where the Navigation enabled message is blocked between AAWireless and the HU. We could then have both Google Maps/Waze enabled and also the stock HU navigation.
My HU knows when navigation is enabled so there must be a flag/message telling the HU this from the phone. I don't have a clue on AAWireless protocols as to how hard this would be.

**Comment by Snirpo** [comment]
Not sure if this is possible, we will investigate.

**Comment by Pixel-Gavin** [comment]
Thanks - the HU must somehow know when there's active navigation going on, but obviously it depends how deep you can go into this.

**Comment by Snirpo** [comment]
Unfortunately we can't do this.
