### ISSUE TITLE
Mazda: not connecting

### ISSUE THREAD

**Issue by muengger** [cpebit/aawireless-issues#89]
**Describe the bug**
Im not able to connect my mazda over AAWireless with new google pixel 6
by cable it works but not on wireless. 
if the phone connect with  AAWireless the AA start's on phone but not on car .there is noting visible happen.

**Car (please complete the following information):**
Mazda 3 BM 2013

**Head-unit (please complete the following information):**
 - Mazda MZD FW.V 70x 

**Smartphone (please complete the following information):**
Google Pixel 6
 - Android version 12

**Comment by Snirpo** [comment]
We will investigate.

**Comment by muengger** [comment]
Just ask if you need some more informations

**Comment by bomke** [comment]
Might be related... My Pixel 6 only works in passthrough mode with an 2019 Opel Adam (otherwise it only displays the prompt to continue the setup on the car's screen, but nothing happen there). Weird thing is: The Galaxy S20FE of my wife which also runs Android 12 only runs WITHOUTpassthrough mode (otherwise same thing as with the Pixel -> prompts the continue on car screen, but nothing there).

Is there anything already known about Android 12 issues? Already tried the latest beta 3 of 12.1 and the latest AA 7.4.x beta on the Pixel, but still no luck...

**Comment by Chrisvng** [comment]
Having the same issue here on my Mazda 6 2019 and Samsung A52s running on andriod 12. Am not able to launch AA on the car's headunit (flashing blue LED). Have also raise this issue in a separate issue log yesterday. Hoping to get OTA update for this.

**Comment by juanfdp** [comment]
Two things happend to me, first, my galaxy s21+ only works with wireless, if I connect to cable, nothing happends, only charging

Second, AA only works in passthrough mode enabled, in passthrough mode disabled I had tried in all USB modes and prompts to continue on car screen, but nothing happend in the head unit

Mazda MZD, FW.V 70.00.367
Mazda CX3 2017
Galaxy S21+ Android 12 One UI 4.1

**Comment by hyperbit00** [comment]
Same here in my mazda6 2017.

Only works with passthrough enabled since 2.0.

I want to Go Back to 1.8/ 1.9 please give instructions for all without contacting Support!

**Comment by Snirpo** [comment]
@hyperbit00 have you already been downgraded to 1.8? If so, does it work without passthrough now?

**Comment by juanfdp** [comment]
> Two things happend to me, first, my galaxy s21+ only works with wireless, if I connect to cable, nothing happends, only charging
> 
> Second, AA only works in passthrough mode enabled, in passthrough mode disabled I had tried in all USB modes and prompts to continue on car screen, but nothing happend in the head unit
> 
> Mazda MZD, FW.V 70.00.367 Mazda CX3 2017 Galaxy S21+ Android 12 One UI 4.1

This happen to my in 1.8/2.0 Firmaware

**Comment by Sloth-on-meth** [comment]
My Peugeot 208 only works with passthrough mode on my Pixel 6

**Comment by Norbert1207** [comment]
Hi, I run into the same problem:
It seems the device can't connect to HU. The Led blinks green, then blue and then it starts the hole process again. 

My car is a Mazda CX-5 2020 with HU version 70.00.367 and Xiaomi Redme Note 10 Miui 13.

I still have tried all tips described in your faq and of your app with no luck. 
In the very first time I ' ve got it working (version 1.12), but after the update to 2.0.1 the connection failed.
I looking forward to downgrade to 1.12. (Contact support)

**Comment by Norbert1207** [comment]
So, now I am on 1.12 and first it showed the same behaviour.  Then, I got a tip from an other user to do a factory reset of the HU. That worked, AA starts, but only with pass through mode enabled.

**Comment by muengger** [comment]
I also made it working. With factory reset of MZD and passthrough mode. But it's not possible to do that with 2 different mobiles.

**Comment by Psp104** [comment]
> Hi, I run into the same problem: It seems the device can't connect to HU. The Led blinks green, then blue and then it starts the hole process again.
> 
> My car is a Mazda CX-5 2020 with HU version 70.00.367 and Xiaomi Redme Note 10 Miui 13.
> 
> I still have tried all tips described in your faq and of your app with no luck. At the very first time I ' ve got it working (version 1.12), but after the update to 2.0.1 the connection failed. I'm looking forward to downgrade to 1.12. (Contact support)

Hello,


I also have 2020 Mazda cx-5. Before updating to 2.0 AAW firmware, my AAW (firmware 1.8x) and with HU version 700.00.335 worked fine without any issues.

After updating to AAW firmware 2.0, my HU failed to connect to AAW no matter what I did.

So, I did update my HU to 74.00.311 at Mazda dealership. Factory reset the HU. Removed Android auto cache and data from phone. Did the whole installation of AAW. Then, I enabled pass-through mode. After all those steps, my AAW works flawlessly now.

I hope this help with fellow Mazda owners and hoping future firmware would fix the issue with Mazda HU.

**Comment by Psp104** [comment]
> Im having issue on my Mazda CX5 2019 and Samsung S22 Ultra. Am not able to launch AA on the car's head unit (flashing blue LED). Any thing I change doesn't seem to work

What is your Head Unit Version? It is something like 700.00.335. Try updating it from Mazda dealership to the most current one to 704.00.311

**Comment by irwing-reza** [comment]
> Im having issue on my Mazda CX5 2019 and Samsung S22 Ultra. Am not able to launch AA on the car's head unit (flashing blue LED). Any thing I change doesn't seem to work

I finally got mine working on Sunday.

Same as you Mazda CX5 2019 and S22 Ultra.

Steps:
1. Did a reset on the head unit.
2. Reset on AA Dongle, AA Wireless App and Android Auto.
3. Delete previous Bluetooth connections to head unit and AA Wireless Device.
4. Do not connect device to head unit.
5. Start dongle setup.
6. If it doesn't connect change settings to this:
    - USB Mode to MTP
    - Passthrough Enabled
7. You should now be able to connect.
