### ISSUE TITLE
OTA update 180 loops

### ISSUE THREAD

**Issue by MariDGb** [cpebit/aawireless-issues#90]
The 180 update loops back to download after device reboot. Then Android Auto has very weak WiFi and apps do not work properly. I didn't have this issue with previous updates.

Also, this happens only in the car. From a wall outlet the app says 1.8.0 and no updates available.

Update: resolved by changing phone settings.

**Comment by TheJeterLP** [comment]
If you resolved your issue, could you close it on github please?

**Comment by MariDGb** [comment]
Done!

Thanks,

Marianne

**Comment by TheJeterLP** [comment]
It's actually still open :D

**Comment by MariDGb** [comment]
It is now 😃
