### ISSUE TITLE
Need a way to quickly switch between paired phones

### ISSUE THREAD

**Issue by ZainAjam** [cpebit/aawireless-issues#91]
With at least two drivers of the same car (and sometimes with all the phones in the car during the drive), the device connects to the last paired device with no easy way to switch to the correct driver. At the moment, I have to find all the phones that I don't want to connect to the aawireless and disable bluetooth and wifi on all of them, so that it can connect to the one that has its bluetooth and wifi enabled. Very clunky and burdensome on all the users who are not the driver. Need a block in the AAwireless app that says "Paired Phones" (or similar) and then a way to directly select the phone to use inside that block. An then, to take it even further, would be good to have an android widget for the app that can be placed on a home screen to quickly select the phone to connect

**Comment by Snirpo** [comment]
Will be fixed in firmware 2.0 with paired phone management.
