### ISSUE TITLE
AA Wireless constantly disconnecting

### ISSUE THREAD

**Issue by Chazzba** [cpebit/aawireless-issues#92]
Hi 

Is anyone able to help? I recently got my AA wireless but it keeps disconnecting randomly. 

Phone is samsung galaxy s21
Car is 2021 Mazda cx30

Any help is much appreciated ! Otherwise I'm selling it because it's useless to me!

**Comment by Snirpo** [comment]
This is not the place for troubleshooting. Please contact support@cpeb.it for help.
