### ISSUE TITLE
Calls audio comes from the phone and not from car system 

### ISSUE THREAD

**Issue by robbyar** [cpebit/aawireless-issues#93]
**Describe the bug**
When Android Auto is connected with aawireless, all the audio (Google assistant, music streaming) comes from car system, except of the audio of the calls that comes out from phone. I have to manually select car system from bluetooth menù of the phone in order to have calls audio from the car system.

**Screenshots**

**Car (please complete the following information):**
 - Renault Kadjar

**Headunit (please complete the following information):**
 - Renault Rlink

**Smartphone (please complete the following information):**
 - Device: Xiaomi MI A1
 - Android 9

**Additional context**
I think the problem is that aawireless needs calls enabled in bluetooth settings. So when the call comes, the audio is redirected to aawireless and not to car system. If I turn off calls in aawireless bluetooth settings, the calls audio comes from car system, but android auto won't start

**Comment by Snirpo** [comment]
Please enable dongle mode in firmware > 2.0. Dummy handsfree will be disabled in this mode and this problem will be gone.
