### ISSUE TITLE
Looking for Android auto

### ISSUE THREAD

**Issue by Thibaut911** [cpebit/aawireless-issues#94]
**Describe the bug**
Sometimes connect without any issue then suddenly disconnect, black screen, not connect to the head unit anymore.
Try to reconnect and keep searching for Android auto. Bluetooth still connect.

**Car (please complete the following information):**
 - Porsche 911-992 Turbo S

**Smartphone (please complete the following information):**
 - Samsung S Fold 2
 - Android version 12

**Comment by Snirpo** [comment]
Does this issue still exist?
