### ISSUE TITLE
Unable to connect to car headunit

### ISSUE THREAD

**Issue by Chrisvng** [cpebit/aawireless-issues#95]
**Describe the bug**
Hi, I am able to connect to Aawireless device on both bluetooth and WiFi. However, I am unable to connect to the car's headunit (flashing blue light). Noticed on my phone that is says that it's connected to andrio auto and another saying that it's searching for Andriod auto (Screenshot attached).

Have tried different permutations of the settings on aawireless but nothing seems to work. 

Current settings on aawireless are:
USB mode: Default
Passthrough: Off
Force 2.4GHz: On
Start / Stop: On (selected Mazda car head unit)
Rest of the settings are not selected.

Have also included some other images for reference

**Screenshots**
![Screenshot_20220216-223451_Nova7](https://user-images.githubusercontent.com/100753112/156311007-f58321a3-3563-42ba-b61e-ddd1343531e4.jpg)
![Screenshot_20220216-224524_AAWireless Config](https://user-images.githubusercontent.com/100753112/156311014-a1dc52fd-3696-40f8-a385-8af079c69fa8.jpg)
![Screenshot_20220223-214011_Android Auto](https://user-images.githubusercontent.com/100753112/156311016-1d7c4f55-6b4c-4aea-8962-8d6ac7a9629e.jpg)
![Screenshot_20220223-213833_Settings](https://user-images.githubusercontent.com/100753112/156311020-4826a6ce-1a5f-4acd-9b2e-4e52e79e8e19.jpg)
![Screenshot_20220223-214015_Android Auto](https://user-images.githubusercontent.com/100753112/156311022-04986bdf-b1e2-4dce-a901-138aea9fb53c.jpg)

**Car (please complete the following information):**
 - Mazda 6 2019

**Headunit (please complete the following information):**
 - Mazda MZD Connect running software 70.000.367

**Smartphone (please complete the following information):**
 - Device: Samsung A52s
 - Android version 12

**Additional context**

**Comment by Snirpo** [comment]
Please try another cable, blinking blue means there's no communication on the head unit side.
