### ISSUE TITLE
Maps Feature VW Group Virtual Cockpit

### ISSUE THREAD

**Issue by projek01** [cpebit/aawireless-issues#98]
The virtual cockpit (digital dashboard) on many VW group cars will display a beautiful map while you are driving. However, it gets disabled when Google Maps or Waze is open on Android Auto.

The car is checking for something along the lines of "navigation status". I hope there is a way to hide the "navigation status" or set it to false all of the time as a feature.

Thanks guys!

**Comment by Snirpo** [comment]
Unfortunately this is a car side limitation, happens in most cars.
